### ISSUE TITLE
Site-specific UA overrides don't work

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/moebius#107]
Despite setting `general.useragent.site_specific_overrides` to true, this doesn't actually work.

**Comment by JustOff** [comment]
See [bug #896114](https://bugzilla.mozilla.org/show_bug.cgi?id=896114) and [Issue #873](https://github.com/MoonchildProductions/Pale-Moon/issues/873).

**Comment by wolfbeast** [comment]
That doesn't matter. That is to prevent general.useragent.override from overriding site-specific ones. Site-specific ones don't work at all right now.

**Comment by wolfbeast** [comment]
896114 is probably the issue though. I could have sworn that reversal was already done but maybe I'm mistaken.

**Comment by wolfbeast** [comment]
Resolved by a38d9bc69572082ae2952facd012655a8f99bd31
