### ISSUE TITLE
Re-implement WebP decoding

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/moebius#11]
Port WebP decoding from Pale Moon to UXP.

**Comment by wolfbeast** [comment]
Solved by 214a6ede85ffba779ca663b3be49550c76325321

**Comment by Happy-Ferret** [comment]
I know there is probably no official support for animated webp images (at least there wasn't in Pale Moon, last I checked) but the following animation is rendered for a few frames before it fails with an ```image corrupt or truncated```

http://littlesvr.ca/apng/images/BladeRunner.webp

**Comment by wolfbeast** [comment]
Animation support for WebP in Möbius is currently experimental. It probably needs a few more tweaks to become more robust.
