### ISSUE TITLE
[suggestion] URL parser - improvements

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/moebius#128]
## 1) Don't allow empty host name

Ad https://url.spec.whatwg.org/#url-representation

> ...lists [dis]allowed URL’s scheme / host combinations.
`scheme = non-"file" special` / `host = empty host`

## 2) Stop preserving empty passwords

Ad https://github.com/whatwg/url/pull/186

**Comment by wolfbeast** [comment]
ONE ISSUE AT A TIME.
