### ISSUE TITLE
"Clear Recent History" - "Offline Website Data": Doesn't clear QuotaManager storage

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/moebius#139]
See:
https://bugzilla.mozilla.org/show_bug.cgi?id=1047098

See also:
https://github.com/MoonchildProductions/Pale-Moon/pull/1359

**Comment by JustOff** [comment]
Please note that my implementation in [Pale-Moon#1359](https://github.com/MoonchildProductions/Pale-Moon/pull/1359) significantly differs from what was done in [bug #1047098](https://bugzilla.mozilla.org/show_bug.cgi?id=1047098). We need to decide which one is more suitable for Mobius.

**Comment by wolfbeast** [comment]
For Möbius it's probably better to stick to what Mozilla has done if it can be grafted easily.

**Comment by JustOff** [comment]
Well, let's see how this will be landed into ESR 52 first.

**Comment by janekptacijarabaci** [comment]
See also:
https://bugzilla.mozilla.org/show_bug.cgi?id=1252998

**Comment by wolfbeast** [comment]
@janekptacijarabaci I've taken care of that with ded198c8b6fee0108c54c4380d551b99fce0434f  -- makes sense to include offline app data with "forget"

**Comment by JustOff** [comment]
Unfortunately I currently can't take care of this task, but I have to note that Mozilla finally prepared [all the necessary](https://bugzilla.mozilla.org/show_bug.cgi?id=1047098#c99) to uplift it to 52 ESR.

**Comment by wolfbeast** [comment]
Sounds to me like Mozilla's solution is becoming very high risk with a bunch of additional uplifts required. I'd rather go for the KISS solution we adopted in Pale Moon, in the front-end, instead.
