### ISSUE TITLE
Hotfix add-on

### ISSUE THREAD

**Issue by JustOff** [MoonchildProductions/moebius#147]
I just got the Hotfix add-on for Firefox in Basilisk ~~- it was silently installed in the background (!)~~. Luckily, the installation attempt failed.
```
1507927641901	addons.update-checker	WARN	Update manifest for aushelper@mozilla.org did not contain an updates property
1507927642487	addons.xpi	WARN	Add-on firefox-hotfix@mozilla.org is not compatible with application version.
1507927642490	addons.xpi	WARN	Add-on firefox-hotfix@mozilla.org is not compatible with application version.
1507927656842	addons.xpi	ERROR	Attempted to load bootstrap scope from missing directory C:\BasiliskPortable\User\Basilisk\Profiles\Default\extensions\firefox-hotfix@mozilla.org.xpi  Log.jsm:748
NS_ERROR_FILE_NOT_FOUND: Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIFile.isDirectory]  XPIProvider.jsm:1617
```
 I think we have to get rid of this malware like it was done in Pale Moon (see https://github.com/MoonchildProductions/Pale-Moon/issues/844).

We probably need to wipe `aushelper@mozilla.org` as well (see [new Firefox system add-on](https://www.ghacks.net/2016/11/04/application-update-service-helper/)).

**Comment by wolfbeast** [comment]
> We probably need to wipe aushelper@mozilla.org as well (see new Firefox system add-on).

I don't think we have that system add-on in our tree.
