### ISSUE TITLE
Implement virtual/lazy tabs

### ISSUE THREAD

**Issue by mzso** [MoonchildProductions/moebius#150]
Hi!
I would like to put this out there, because it's one of the best performance improvements in Firefox recently. And I think they were implemented later than "early 2017" when moebius was forked. Only landed in FF55.

These are the most relevant bugs I think:

https://bugzilla.mozilla.org/show_bug.cgi?id=1345090
https://bugzilla.mozilla.org/show_bug.cgi?id=906076

**Comment by wolfbeast** [comment]
Lazy tabs are primarily important because IPC startup and init is a slow process. This is N/A for us because we don't use e10s; Our startup times are sufficiently low as they are without adding a procedure that takes porting of a couple dozen dependent bugs.

**Comment by mzso** [comment]
So no multi process? Ouch.

**Comment by wolfbeast** [comment]
Nothing ouch about that. Multi-process messaging overhead and snags are terrible, from just about every angle. Focusing on making things multi-threaded and multi-core/parallel at the lower level is a much better approach which we will be focusing on.

**Comment by mzso** [comment]
[**@wolfbeast**](https://github.com/wolfbeast) commented on [2017. okt. 16. 22:04 CEST](https://github.com/MoonchildProductions/moebius/issues/150#issuecomment-337021141 "2017-10-16T20:04:45Z - Replied by Github Reply Comments"):
> Nothing ouch about that. Multi-process messaging overhead and snags are terrible, from just about every angle. Focusing on making things multi-threaded and multi-core/parallel at the lower level is a much better approach which we will be doing.

Hmmm... So you mean you'll have a different sort of parralel processing? How will that work?
By "lower level" you mean you'll be doing it with threads withing the browser's process? Doesn't that have the same issues with messaging as such as multi processes?

Any github issues (or something else) I can follow?

**Comment by wolfbeast** [comment]
This is best discussed on the forum - this issue tracker is not for that.

**Comment by mzso** [comment]
(Is there a forum? On the PM forum I don't see a Basilisk/Moebius section)

**Comment by wolfbeast** [comment]
Use the Pale Moon forum. UXP/Möbius is also Pale Moon's future, after all, and this has come up as a point of discussion before.
