### ISSUE TITLE
Disable Google Safe Browsing in Basilisk releases.

### ISSUE THREAD

**Issue by JustOff** [MoonchildProductions/moebius#153]
Log: `POST https://safebrowsing.google.com/safebrowsing/downloads`, stack:
```
PROT_ListManager.prototype.makeUpdateRequestForEntry_ resource://gre/components/nsUrlClassifierListManager.js:481:8
PROT_ListManager.prototype.makeUpdateRequest_ resource://gre/components/nsUrlClassifierListManager.js:461:5
newfn resource://gre/components/nsUrlClassifierLib.js:52:12
```
I think this component should be at least disabled and hidden in the options if not removed completely.

**Comment by wolfbeast** [comment]
Basilisk is not Pale Moon. Basilisk will be offering a range of services that Firefox offers, including Google safebrowsing, Firefox Accounts, and similar. If the service works, there's no reason to disable it.

**Comment by JustOff** [comment]
But Basilisk don't have api-key for SafeBrowsing, so what is the reason to waste resources for useless requests?

**Comment by wolfbeast** [comment]
It can be disabled at build time. It won't require code changes.

**Comment by wolfbeast** [comment]
Hmm.. apparently Mozilla removed this build option, even though it's still in mozilla.configure.

**Comment by wolfbeast** [comment]
This needs to be reverted to restore build-time choice of safebrowsing:
https://hg.mozilla.org/mozilla-central/rev/d3ef59a2f50a -- this doesn't graft cleanly at all, so will be a PITA.

Alternatively, the easy option is to simply disable it in prefs and clear the safebrowsing providers.

**Comment by JustOff** [comment]
Thank you.
