### ISSUE TITLE
Use the Preprocessor instead of AppConstants

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/moebius#156]
Mozilla has taken it upon themselves to make what are build-time configuration options into run-time evaluation through the use of AppConstants.

This is problematic:
- It inflates target code size
- It increases complexity with more than a 1000 individual run-time checks
- It reduces performance because of said checks
- It makes no difference for parts where run-time checks can't be used and preprocessing is needed anyway, creating a big mess of code that is half build-time, half run-time.

We need to return to preprocessing and reducing object code size that way. Preprocessors exist for a good reason.
If we want UXP to be usable for Pale Moon and other applications, this is likely going to be a hard and critical requirement.

Part of this work will be moving configure defines back to makefile configure from the pythonification `moz.configure`. 

To start off, we'll need to revert the AppConstants in `toolkit\modules\AppConstants.jsm` and the sites where these are used to normal preprocessor `#ifdef`s; probably one at a time to be safe and not cause hard-to-trace breakage.

**Comment by mattatobin** [comment]
The part of AppConstants that overlaps with #19 specifically reinstating MOZ_PHOENIX and establishing MC_BASILISK and MC_PALEMOON will be handled by me when that time comes.. Basically anything past [Line 314](http://xref.palemoon.org/moebius-trunk/source/toolkit/modules/AppConstants.jsm#314).

Otherwise, anyone who wants to tackle one of them, I wish you luck!

**Comment by wolfbeast** [comment]
Anyone who wants to help with this is welcome. This isn't very difficult work but does need some understanding of how the preprocessor is used in our code. If you make pull requests please directly reference this issue in it.

**Comment by mattatobin** [comment]
Will be completed in `Take 2`
