### ISSUE TITLE
Remove region-specific selection of default search engines.

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/moebius#163]
This is a Mozilla-ism that defaults to probing a Mozilla server to get non-default server selections for search in an undocumented way for individual locales (the default way is apparently "not good enough" to have search engines and orders set in locale-specific properties).

Prefs are even used to set individual fallbacks in case the lookup fails and a custom list can't be grabbed from a URL.

Reference prefs: `browser.search.geoSpecificDefaults.*`, `browser.search.defaultenginename.{locale}` and `browser.search.order.{locale}.{n}`.

- [X] Disable geo-specific changes and the Mozilla service lookup for release
- [ ] Remove the relevant code

All this needs to go.
Blocks #66.

**Comment by trav90** [comment]
I can confirm that the two commits referenced above result in DDG being the default search engine in the en-US local as intended (tested with a new profile).
