### ISSUE TITLE
Publish first public version of Basilisk

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/moebius#164]
**Checklist:**
- [x] Prepare binaries
- [x] Sign binaries (new script)
- [x] Package
- [x] Verify operation of final packaged versions (beta team)
- [x] Verify operation of AUS
- [x] Prepare download page
- [x] Mirror packaged versions for install to servers (new script)
- [x] Prepare initial publication statement/announcement
- [x] Put everything live
- [x] Have a beer

**Comment by wolfbeast** [comment]
@mattatobin 
AUS required an addition to the script because `%BUILD_TARGET%` in VS2015 is different (it tacks on `-x64` for the arch of the compiler used).

Resulting array:
```PHP
    'buildTarget' => array(
        'winnt_x86-msvc' => 'win32',           // VS2013
        'winnt_x86_64-msvc' => 'win64',        // VS2013
        'winnt_x86-msvc-x64' => 'win32',       // VS2015
        'winnt_x86_64-msvc-x64' => 'win64',    // VS2015
        'linux_x86_64-gcc3' => 'linux-x86_64'
    ),
```

**Comment by mattatobin** [comment]
I see.. Least the fix was easy!

**Comment by wolfbeast** [comment]
Everything is now live. Sharks ahoy!

**Comment by adeshkp** [comment]
Still no beer! :laughing:

**Comment by wolfbeast** [comment]
It's in the fridge! I don't like it warm ;)

**Comment by wolfbeast** [comment]
![chimay-bleue_-blue_beer_900](https://user-images.githubusercontent.com/3359132/32961869-99dd334e-cbca-11e7-85f4-d504b283a605.jpg)
