### ISSUE TITLE
CSP 3 - support for "worker-src"

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/moebius#168]
https://www.w3.org/TR/CSP3/#directive-worker-src

> The worker-src directive restricts the URLs which may be loaded as a Worker, SharedWorker, or ServiceWorker.

Impact of the improvement:
- Improve security/compatibility?

**Comment by wolfbeast** [comment]
It would be nice if someone can verify this (e.g. setting up a restrictive CSP on a page that requires worker-src to be defined).

**Comment by janekptacijarabaci** [comment]
An example: https://self-repair.mozilla.org/en-US/repair
