### ISSUE TITLE
Reinstate GKMEDIAS_SHARED_LIBRARY

### ISSUE THREAD

**Issue by mattatobin** [MoonchildProductions/moebius#17]
This will take some major research but it should be a goal.

---
- [ ] Restore Configure Flags
- [ ] Restore mozbuild logic
- [ ] Restore symbols.def.in and update it

**Comment by mattatobin** [comment]
- Disabled @ Mozilla by https://bugzilla.mozilla.org/show_bug.cgi?id=922912
- Reverted and fixed in Tycho by https://github.com/MoonchildProductions/Pale-Moon/commit/1f0c715b4de14e9847cb4d6e44d1a32c7a08fcca
- Apperently busted badly @ Mozilla by https://bugzilla.mozilla.org/show_bug.cgi?id=1051146
- And completely removed @ Mozilla by https://bugzilla.mozilla.org/show_bug.cgi?id=1216444

**Comment by wolfbeast** [comment]
So what is pocketsphinx, and why do we need it?

**Comment by mattatobin** [comment]
Something related to webspeech and yeah I agree.. We had to sort that on Tycho before only took a few hours if I recall..
