### ISSUE TITLE
Installer won't start Basilisk at the end if firefox is running. Claims Basilisk has a running instance.

### ISSUE THREAD

**Issue by mzso** [MoonchildProductions/moebius#170]
It seems obvious that it checks for a firefox.exe running. I can start Basilisk manually.

**Comment by wolfbeast** [comment]
Thanks. Probably one of the many places where Mozilla has hard-coded firefox instead of `APP_NAME`.

**Comment by wolfbeast** [comment]
The installer checks for a WindowClass being `FirefoxMessageWindow` -- this class is dynamically created from `appName + "MessageWindow"` -- I've updated the defines of the Basilisk installer to have the correct App names and class names there; one of the branding locations that is in an illogocal place and slipped under the radar.
