### ISSUE TITLE
Cannot import settings and data from Firefox

### ISSUE THREAD

**Issue by robertc** [MoonchildProductions/moebius#172]
When running for the first time I get the option to import settings from IE, Chrome and Chrome Canary but not any of my existing Firefox profiles.  Being able to automatically import from Firefox would be a useful feature for people looking to switch from Firefox.

**Comment by wolfbeast** [comment]
It's not possible because Firefox has made breaking changes to their profile structure. There is no migration path that is meaningful from current Firefox to Basilisk.

**Comment by wiesl** [comment]
Copied my Firefox 57 profile to Basilisk and works well so far.

Only had problems with addons, but worked well:
Add-ons disabled? Including UBlock Origin??
https://forum.palemoon.org/viewtopic.php?f=61&t=17398&sid=fff9c725c05452048ca36fdfab205690
I think, there is a problem with the blocklist.
If you open about:config, change the value of extensions.blocklist.enabled from true to false and restart the browser, then your add-ons are not disabled.

**Comment by wolfbeast** [comment]
@wiesl You copied a Firefox 57 blocklist along with your profile. That is causing your problems -- the blocklist doesn't apply to Basilisk and will block incorrectly. Disabling the blocklist feature completely is not recommended.

**Comment by wiesl** [comment]
What settings must be modified to solve it without disabling the blocklist feature completely?

**Comment by wolfbeast** [comment]
Just remove the blocklist XML from your profile? Or is Mozilla serving us an incorrect blocklist regardless of reported version?

**Comment by robertc** [comment]
> There is no migration path that is meaningful from current Firefox to Basilisk.

The only things that are meaningful to me are my passwords and history, is that data totally incompatible?

**Comment by wolfbeast** [comment]
You can copy passwords across manually with relative ease (see the forum for instructions/help) -- history isn't possible because the places database structure was changed and isn't backwards compatible.
