### ISSUE TITLE
Fix up about: page

### ISSUE THREAD

**Issue by KNTRO** [MoonchildProductions/moebius#173]
Internal version ID text —gray colored actually— is overlapping the logo.

![basilisk](https://user-images.githubusercontent.com/2568821/32960548-0211776c-cba4-11e7-8f84-02611b1b8cb7.png)

**Comment by wolfbeast** [comment]
On which page is this, exactly?

**Comment by KNTRO** [comment]
At _about:_

**Comment by wolfbeast** [comment]
Ah, and I see more issues that need de-Mozifying there.

**Comment by KNTRO** [comment]
> "Build identifier" is a misnomer.

Wait, are you saying _Basilisk/20171112_ is not the supposed to be version? :rofl: I have already promoted Basilisk like that, even in the Spanish Wikipedia entry about _Goanna_. :sweat_smile:

**Comment by wolfbeast** [comment]
? "build identifier" lists the entire user agent string.
and the version is 2017.11.12 (see about box) -- or 2017.11.13 for Linux.

**Comment by janekptacijarabaci** [comment]
Ad `about:` - also throws an errors in Browser Console:
```
formatURLPref: Couldn't get pref: app.releaseNotesURL
uf_formatURLPref resource://gre/components/nsURLFormatter.js:143:7
chrome://global/content/about.js:8:23

formatURLPref: Couldn't get pref: app.vendorURL
uf_formatURLPref resource://gre/components/nsURLFormatter.js:143:7
chrome://global/content/about.js:15:17
```

**Comment by mattatobin** [comment]
I'd prefer moebius toolkit about: page was aligned with what we have done in Tycho..

**Comment by wolfbeast** [comment]
Taking this. I need to focus on some design work to prevent brainmelt in C++ ;)
