### ISSUE TITLE
Font rendering bug on Linux

### ISSUE THREAD

**Issue by CandyGumdrop** [MoonchildProductions/moebius#175]
Firefox 52 switched to use the Skia library for rendering by default, and Skia uses FreeType2 for font rendering on Linux.  However, Skia has relied on some undocumented internals of FreeType2 which changed in FreeType 2.8.1, which causes rendering glitches.  Upstream Skia has since fixed this and this fix in Skia has since been included in upstream Firefox and Chromium.  Users of FreeType 2.8.0 or older are not affected.

![Screenshot of font rendering glitches][3]

[Here][1] is the Skia bug report and [here][2] is the patch to fix Skia.

It is possible to work around this bug in `about:config` by changing both `gfx.canvas.azure.backends` and `gfx.content.azure.backends` from `skia` to `cairo`.

[1]: https://bugs.chromium.org/p/skia/issues/detail?id=6663
[2]: https://skia.googlesource.com/skia/+/d1f2d15b36f6a6a9d199581b998a7ca924a1f1a8%5E%21/
[3]: https://user-images.githubusercontent.com/5421362/32965304-01b87264-cbce-11e7-938e-c3efe7c2dbf4.png

**Comment by wolfbeast** [comment]
Thanks for the pointers -- saved me a bunch of time trying to find the right commit.

**Comment by wolfbeast** [comment]
Not possible for me to test this, so if someone can make a linux build from master and verify, that would be great.

**Comment by wolfbeast** [comment]
Reopening until verified.

**Comment by CandyGumdrop** [comment]
Just tried building the repository but it looks like something's not quite right.  This particular font rendering bug appears to be fixed, however.

Before (a7b697388f891c585dc4a5f4d3f6352ef412bcb1):

![2017-11-17-232114_1228x787_scrot](https://user-images.githubusercontent.com/5421362/32973311-a885edc2-cbee-11e7-8461-b876700817a7.png)

After (d092a1fe8017f104d9de0463fd75349c63155a3d):

![2017-11-17-232307_1226x787_scrot](https://user-images.githubusercontent.com/5421362/32973321-b40e9b94-cbee-11e7-96ad-ffc0f7cffb61.png)

All I did was clone the repository and run `./mach build` and `./mach run`.  Am I missing some important configuration or otherwise doing something stupid?  I'm using gcc-7.2.0 on Gentoo.

**Comment by wolfbeast** [comment]
yeah building an unconfigured tree will get you all sorts of LSD-trippin places.
@trav90 maybe you can help @CandyGumdrop out with a proper config so this bug can be verified and closed?

**Comment by trav90** [comment]
@CandyGumdrop you need to create a .mozconfig file as well before executing `./mach build`. Please create this file in the root of repo witht he following contents for a _similiar_ (but not exact!) configuration to official releases:

```
mk_add_options AUTOCLOBBER=1

mk_add_options MOZ_OBJDIR=/$HOME/build/Basilisk/
ac_add_options --enable-application=browser
export MOZILLA_OFFICIAL=1

ac_add_options --enable-official-branding
ac_add_options --enable-optimize="-O2 -msse2 -mfpmath=sse"

ac_add_options --disable-updater
ac_add_options --disable-tests
ac_add_options --disable-parental-controls
ac_add_options --disable-accessibility
ac_add_options --disable-crashreporter

export MOZ_TELEMETRY_REPORTING=
MOZ_ADDON_SIGNING=
MOZ_REQUIRE_SIGNING=
mk_add_options MOZ_PGO=

ac_add_options --enable-jemalloc
ac_add_options --with-pthreads
ac_add_options --enable-strip

ac_add_options --x-libraries=/usr/lib
```

Also please note that building with GCC 7.x is untested and may not produce the desired results.

**Comment by adeshkp** [comment]
Still not fixed. This is what I get on first launch.
https://i.imgur.com/lKKB2rN.png


This seems to be unrelated, but I get following errors on console:
```
$ basilisk/basilisk-bin --no-remote --profile /tmp/bprofile
*************************
A coding exception was thrown in a Promise resolution callback.
See https://developer.mozilla.org/Mozilla/JavaScript_code_modules/Promise.jsm/Promise

Full message: ReferenceError: CloudSync is not defined
Full stack: _promiseUpdateUI/<@chrome://browser/content/browser-syncui.js:173:1
process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:917:23
walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:801:7
scheduleWalkerLoop/<@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:737:11
openModalWindow@resource://gre/components/nsPrompter.js:364:5
openPrompt@resource://gre/components/nsPrompter.js:579:9
confirmEx@resource://gre/components/nsPrompter.js:720:9
confirmEx@resource://gre/components/nsPrompter.js:79:16
prompt@resource://app/components/nsBrowserGlue.js:2675:16
BG__onWindowsRestored/<@resource://app/components/nsBrowserGlue.js:1151:11
```

**Comment by CandyGumdrop** [comment]
Thank you, @trav90.

All looks good now, with gcc 7 and `-O2 -march=native`:

![2017-11-18-113116_900x847_scrot](https://user-images.githubusercontent.com/5421362/32979827-13fc9014-cc54-11e7-8750-ec9e5d8d3249.png)

@adeshkp That doesn't look to me like it has any of the graphical artifacts caused by this bug.  Maybe it's just your FreeType2 config or the particular font you have.  Does it look the same as with the previous commit, and does it look the same with cairo vs skia?

**Comment by wolfbeast** [comment]
@adeshkp the font artifacts you're seeing don't seem to be the same as the original issue in this bug (which seems to be solved here). If there's a continued issue with freetype for you that is clearly a bug in the browser (and not a config problem), then please open a new issue.

**Comment by wolfbeast** [comment]
Thanks for verifying, @CandyGumdrop !
