### ISSUE TITLE
Update to Firefox 56.latest?

### ISSUE THREAD

**Issue by wiesl** [MoonchildProductions/moebius#180]
Current Basilisk is based on Firefox 55 at according to the User-Agent header. Please update to Firefox 56.latest core.

User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Goanna/4.0 Firefox/55.0 Basilisk/20171112

**Comment by wiesl** [comment]
Might be also caused by 57d81765f75d36d99e07a4edb99c373454ffb0a5

**Comment by Sa-Ja-Di** [comment]
Mozilla deconstructed their code base with ongoing releases more and more. There is for sure only a limitation the Basilisk dev team can go forward without losing everything which makes the browser unique - so if you hope that also Firefox 57 and onwards code base will be used, i am afraid you are out of luck.

Most likely wanted elements (features and bugfixes) will be taken and adopted for usage with Basilisk - the same way like it is done also for Pale Moon.

**Comment by wolfbeast** [comment]
User-agent and actual core code do not align and have never aligned. Firefox 55 is a Firefox Compat version at most.

Closing for being a non-issue.
