### ISSUE TITLE
nsIContentPolicy.shouldLoad getted the node parameter with null

### ISSUE THREAD

**Issue by fdsc** [MoonchildProductions/moebius#181]
In FireFox 53 for E10S Mozilla messed up the implementation of nsIContentPolicy. In Basilisk the implementation bad too.

When loading the main page, the callback handler nsIContentPolicy.shouldLoad with the node parameter set to null. This was done to support e10s, but Basilisk is missing e10s rated.

It would be nice to fix this problem so that the node passed by reference to the document as it was in FireFox 52. This feature interferes with my extension.

**Comment by wolfbeast** [comment]
Can you please state the bugzilla bug number where this was changed?

**Comment by fdsc** [comment]
Unfortunately, I couldn't find anything similar. Maybe it wasn't a separate entry in bugzilla, since Mozilla is not a defect, but a planned work.

**Comment by fdsc** [comment]
May be, https://bugzilla.mozilla.org/show_bug.cgi?id=1128798
But really this has stopped working in FF53

**Comment by fdsc** [comment]
It's like https://bugzilla.mozilla.org/show_bug.cgi?id=1339004 . But it is also in 55, not 53
( https://hg.mozilla.org/mozilla-central/comparison/648099cae850/dom/base/nsContentPolicy.cpp )
In General, I can't exactly say where it messed up.

**Comment by janekptacijarabaci** [comment]
AFAIK: https://github.com/MoonchildProductions/moebius/pull/187

**Comment by wolfbeast** [comment]
Just need some verification that this works as-intended now. @fdsc do you have the opportunity to build from source on the master branch? If not i can toss you a private build of Basilisk.

**Comment by fdsc** [comment]
I never built FireFox. I think it would be easier to download the binaries (Windows 7 Intel x64).

**Comment by wolfbeast** [comment]
@fdsc Here's a private build, Winx64.
https://www.dropbox.com/s/6bne0t68mh46geg/basilisk-20171126094230.en-US.win64.zip?dl=0
Let me know when you grabbed it.

**Comment by fdsc** [comment]
It seems the bug is fixed.
