### ISSUE TITLE
Possible updating - doesn't work

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/moebius#182]
Throws an error in Browser Console:
```
XML Parsing Error: syntax error
Location:
https://aus5.mozilla.org/update/3/GMP/55.0.2017.11.12/20171112123433/
WINNT_x86_64-msvc-x64/en-US/release/Windows_NT%206.1.1.0%20(x64)/
default/default/update.xml
Line Number 1, Column 1:
update.xml
```
The file contents are: `Version number 55.0.2017.11.12 is invalid.`

**Comment by wolfbeast** [comment]
We'll have to feed Mozilla version they accept in `media.gmp-manager.url`.
http://xref.palemoon.org/moebius-trunk/source/modules/libpref/init/all.js#5399
I suggest hard-coding `55.0` there.

**Comment by wolfbeast** [comment]
Blocks #66
