### ISSUE TITLE
Main menu - Help

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/moebius#185]
`Basilisk Help`:
=> `https://support.mozilla.org/1/firefox/55.0.0/WINNT/en-US/firefox-help`
(`app.support.baseURL`)

`Basilisk Tour`:
=> `https://www.mozilla.org/en-US/firefox/55.0.0/tour/`
(`browser.uitour.url`)

`Submit Feedback...`: (does not work)
=> [the empty string]
(`app.feedback.baseURL`)

---

Is it right?

**Comment by wolfbeast** [comment]
Yup. Although I guess the feedback can potentially be redirected to the forum now.
