### ISSUE TITLE
Various problems with Firefox add-ons because of 55.0.yyyy.mm.dd format of APP_VERSION

### ISSUE THREAD

**Issue by JustOff** [MoonchildProductions/moebius#189]
* Add-ons with a low maxVersion can't be installed (i.e. pseudo-strict mode, [reported on forum](https://forum.palemoon.org/viewtopic.php?p=127545))
* Add-ons update always fails

This is because `versioncheck.addons.mozilla.org` that is called on add-on install and update doesn't like `55.0.yyyy.mm.dd` format of `APP_VERSION` returned by release versions of Basilisk.

We can easily fix this replacing `Services.appinfo.version` by `Services.appinfo.version.split(".", 2).join(".")` [here](https://github.com/MoonchildProductions/moebius/blob/67dee8622e53453b28d21f4715906227c952edb0/toolkit/mozapps/extensions/AddonManager.jsm#L1329) and [there](https://github.com/MoonchildProductions/moebius/blob/67dee8622e53453b28d21f4715906227c952edb0/toolkit/mozapps/extensions/AddonManager.jsm#L1335) in AddonManager.jsm, but I don't really like such kind of hacks.

**Comment by wolfbeast** [comment]
A simpler solution is to just make sure the appropriate prefs are changed to something it DOES like.

**Comment by JustOff** [comment]
May be it makes sense to reconsider [this approach](https://github.com/MoonchildProductions/moebius/pull/155) for `MOZ_APP_VERSION`?

**Comment by wolfbeast** [comment]
No, it doesn't make sense to reconsider that approach. There's no good alternative to use that won't make it an arbitrary number, and we need to use MOZ_APP_VERSION for compatibility. 

The solution has to simply be to feed external services the type of data they want, not to compromise our internal design choices to satisfy what isn't under our control.

**Comment by wolfbeast** [comment]
I just checked what Firefox services accept, and they accept 3-part version numbers only, because that is the most Firefox will ever use. So there is no way to have unique date-based version numbers in the compatversion that satisfies Mozilla's services. Freezing the number to an accepted arbitrary one is the only way this is going to work.

**Comment by wolfbeast** [comment]
Blocks #66
