### ISSUE TITLE
Do not use generic directory names for platform applications

### ISSUE THREAD

**Issue by mattatobin** [MoonchildProductions/moebius#19]
The intention of UXP is to return the codebase to a place of collaboration, cooperation, and sharing. In that spirit application specific code should not live in generic directories like browser, mail, and suite.

A more practical concern is that it is the intention that Pale Moon will eventually be ported to this platform and neither can really be "browser". So as a matter of policy for UXP applications should be given top level directories that reflect their base product name.

To this end, Basilisk will be moved out of /browser to /application/basilisk.
When it comes to Pale Moon it will live in /application/palemoon

I am considering this bug to be one of on-going progression so I want to leave it open until everything is done.

---
- [x] Rename /browser to /application/basilisk
- [x] Adjust Build System and codebase accordingly
    - [x] Update mozbuild checks for browser directory in MOZ_BUILD_APP
    - [x] Deal with AppConstants.jsm

**Comment by Lootyhoof** [comment]
This would affect pre-existing extensions and themes that build on any product that expects this though, surely? As an example from a development standpoint one would expect the browser's main chrome to exist in `chrome://browser/content/browser.xul`. It's possible of course to keep the same entries in the relevant `jar.mn` files, but that depends to what length this is to go.

**Comment by mattatobin** [comment]
This will not affect chrome or resource registration at all.

**Comment by mattatobin** [comment]
@trav90 Could you build off https://github.com/binoc-central/moebius-contrib/tree/app-work and see if build and packaging as well as cursory functioning is ok on the Linux?

**Comment by mattatobin** [comment]
@khronosschoty is gonna play tryserver..

**Comment by trav90** [comment]
Sorry have been sick in bed all day. Still need Linux verification?

**Comment by mattatobin** [comment]
@trav90 Nah.. Nothing went wrong for @khronosschoty .. It build, packaged, and worked. So we assume it is fine.. if something comes up we can just do a follow up.. But thanks.. and it's totally cool.. You get some rest.

**Comment by trav90** [comment]
Sounds good.
