### ISSUE TITLE
HTML - table - editor (contenteditable)

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/moebius#190]
__Steps to reproduce:__
The test table Link: http://www.w3school.com.cn/tiy/t.asp?f=html_table_test
steps are as follows:
1# use mouse to select the right side table, then copy
2# update tab `<body contenteditable="true">` in left side. then remove the code `<table></table>`, then submit code
3# paste 1#, you will see a text and a table.

__Actual results:__
Copy table, it showed text & table after paste it.

__Expected results:__
Copy table, it should be showed table after paste it.

**Comment by wolfbeast** [comment]
That's an oddly-specific STR ;P
I wonder how people actually found out about this bug.
