### ISSUE TITLE
Implement pointerup and pointerdown PointerEvents

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/moebius#194]
__Steps to reproduce:__

`about:config`:
`dom.w3c_pointer_events.enabled` = true

Go to: https://9anime.to/watch/dgray-man-dub.q2wj/jv97x4

__Expected behavior:__
Hit full screen, it full screens.

__Actual behavior:__
No matter what site, when i hit full screen it does not full screen the videos anymore, using the shortcut F key does seem to work still though.

Throws an error in browser console:
```
Request for fullscreen was denied because Element.requestFullscreen()
was not called from inside a short running user-generated event handler.
jwplayer.js
```

See also:
https://webcompat.com/issues/4964

**Comment by wolfbeast** [comment]
Note: Experimental -- preffed off.

**Comment by wolfbeast** [comment]
Assuming fixed with test on PR.
