### ISSUE TITLE
Fonts problem

### ISSUE THREAD

**Issue by SebaK666** [MoonchildProductions/moebius#199]
Basilisk 32-bit, Windows XP.
Something is wrong with the fonts. That's good to see here. Flashes once clear once blurred
fonts clear in my ESR 52 :
![esr](https://user-images.githubusercontent.com/33153803/33087852-0f6eaf6a-ceec-11e7-986e-be087a34c3e0.jpg)

Basilisk:
![basilisk](https://user-images.githubusercontent.com/33153803/33087880-274ce3c2-ceec-11e7-9f07-92249d1878b3.jpg)

Latest version from 21, but previous version was the same

**Comment by mattatobin** [comment]
Basilisk doesn't support Windows XP.

**Comment by wolfbeast** [comment]
> Basilisk doesn't support Windows XP.

I wonder how they got it to run in the first place.

**Comment by mattatobin** [comment]
Alter the subsystem version after the fact most likely or the XP people did a bailisk build..
