### ISSUE TITLE
Search restrictions using the context menu in Basilisk

### ISSUE THREAD

**Issue by Telmesomething** [MoonchildProductions/moebius#200]
After using Basilisk for less than a day I've come across an issue which I find too restrictive to continue using it. It concerns the ability to search a subject be it a word or phrase on a site somewhere using the context menu. It would appear that Basilisk restricts users to searching solely with DuckDuckGo.com as illustrated in this image: http://imgbox.com/g7ddCZeF

I'd already added the same number of search engines I use in Firefox to Basilisk today and these can be viewed in this image: https://imgbox.com/w9vdrFtN

It's simply not practical in my particular case to have to use a search engine to find the same URLs to all of these just to be able to use them. It doubles my workload and can be considered to be a sheer waste of time. 

While I appreciate that the Basilisk developers have to fund their projects in order to survive, restricting users in this particular way is not the right way to go about it IMO. 

I trust the developers will make changes to Basilisk to allow searches using the context menu with other search engines in addition to DuckDuckGo.

**Comment by wolfbeast** [comment]
This is, and always has been, the case for context searches by default in Firefox applications. **It will use whatever is the default search engine.** We have _not_ changed this behavior since the application was forked, and Firefox to this day displays the same behavior.

There are extensions which will allow you to have more than one search engine there, if I recall correctly, but it's not part of core functionality, and never has been.

**Comment by wolfbeast** [comment]
To illustrate, 2 screenshots of the context menu, one from Firefox 52-ESR (with custom-selected DDG default search engine), and one from a stock Firefox 57 (with Google default).

![fx52](https://user-images.githubusercontent.com/3359132/33119540-9c0d49a8-cf6f-11e7-9855-0b992e93eff2.png)
![fx57](https://user-images.githubusercontent.com/3359132/33119541-9c2a4b66-cf6f-11e7-8813-5951ed25583d.png)

**Comment by Telmesomething** [comment]
I'm a great believer in admitting fault and especially so where it concerns myself.

So my sincere apologies for my faux pas in this particular case. I had omitted to install an extension called Context Search: [https://addons.mozilla.org/en-US/firefox/addon/context-search/](url) which adds to option to search with other engines. 

I shall now adorn myself with a tall pointed hat and go and stand in the corner.

**Comment by wolfbeast** [comment]
> I shall now adorn myself with a tall pointed hat and go and stand in the corner.

No worries. Making one mistake and a few wrong assumptions as a result is a trap open to anyone (including myself) and that doesn't make you a dunce :)
