### ISSUE TITLE
Change text color selected item

### ISSUE THREAD

**Issue by SebaK666** [MoonchildProductions/moebius#201]
It is possible change text color more visible when change selected item from black to white in context menu, bookmarks, menu?
Comparison my Firefox and Basilisk:
![comparise](https://user-images.githubusercontent.com/33153803/33143477-42d928c0-cfba-11e7-847f-1efa05090a4b.jpg)

**Comment by JustOff** [comment]
Here's how it looks in my Basilisk:

![2017-11-22_20-43-52](https://user-images.githubusercontent.com/340855/33144514-04af3d58-cfc6-11e7-9f1b-cbcbb4e16c17.png)

**Comment by SebaK666** [comment]
Theme like Windows 98. it depends on the theme? Or settings in about:config? I use always default - in Basilisk is different than Firefox ESR.

**Comment by JustOff** [comment]
I simple use Classic Theme @ Win7 :sunglasses:
What is your OS and OS Theme?

**Comment by SebaK666** [comment]
Windows XP. Basilisk default theme. Name: Default 55.0.0. Basilisk support H.264 for XP  - that's why I found it. No, i changed theme, but always is black text on selected item.

**Comment by JustOff** [comment]
Windows XP is unsupported by Basilisk. You have to direct this issue to the person who made an unofficial build.

**Comment by SebaK666** [comment]
This post gives a link to the Github site at the end:
http://www.msfn.org/board/topic/177125-my-build-of-new-moon-temp-name-aka-pale-moon-for-xp/?do=findComment&comment=1147552
Sorry, I didn't know, I thought would could report bugs here.

**Comment by wolfbeast** [comment]
You're free to report bugs with the official releases or dev tree builds on supported operating systems. In all other cases your first point of contact will have to be whomever modded/patched it and released the unofficial result.
