### ISSUE TITLE
GNU/Linux: Random add-ons report security or stability issues

### ISSUE THREAD

**Issue by KNTRO** [MoonchildProductions/moebius#202]
**UPDATED**.

It first happened on the _Default_ theme, as you can see below.

![pantallazo-2017-11-23 11-46-38](https://user-images.githubusercontent.com/2568821/33178247-47ffaf06-d044-11e7-9926-c6b629c60aec.png)

Right now, that message disappeared from the _Default_ theme and it's on the _uBlock Origin_ add-on.

![pantallazo-2017-11-23 13-34-40](https://user-images.githubusercontent.com/2568821/33182562-52422c1e-d053-11e7-895b-b185dbc73455.png)

If I click on the _More information_ link, it opens a new tab and try to load _null_ at the address bar.

**Comment by wolfbeast** [comment]
I think it's because Mozilla's addon server is on the fritz and doesn't like Basilisk.
