### ISSUE TITLE
Consolidate and improve privacy.resistFingerprinting

### ISSUE THREAD

**Issue by supriyo-biswas** [MoonchildProductions/moebius#203]
Firefox introduced a new preference, `privacy.resistFingerprinting` which applies a wide variety of techniques to prevent fingerprinting of the browser. Some parts of this are already present in Basilisk.

I would suggest integrating `canvas.poisonData` under this new Firefox preference as well as making a few   additions to this feature present in Firefox, such as serving an uniform user-agent.

**Comment by wolfbeast** [comment]
I'm not sure if it's smart to consolidate everything. Canvas data poisoning, for example, has a rather big performance impact for some operations.

Tag #59
