### ISSUE TITLE
Plugin Loading issue

### ISSUE THREAD

**Issue by ianamk** [MoonchildProductions/moebius#204]
Basilisk does not see and load the SumatraPDF plugin while PaleMoon does
the SumatraPDF plugin writes it's info in the registry at
HKEY_LOCAL_MACHINE\SOFTWARE\MozillaPlugins\@mozilla.zeniko.ch/SumatraPDF_Browser_Plugin_x64
is this maybe a Mozilla import issue as the Flash plugin works seeing how Mozilla blacklisted all plugins except for Flash who's info is stored at
HKEY_LOCAL_MACHINE\SOFTWARE\MozillaPlugins\@adobe.com/FlashPlayer

edit
there seams to be a bug with github as it removes the \ before the @ char so the text above displays incorrect as an email address

**Comment by ianamk** [comment]
this issue exists on the x64 builds (I didn't test x86) Basilisk also doesn't load the x64 ms office or adobe aam plugins while palemoon does, I believe this is related to the fact that the 64bit Firefox blacklisted all npapi plugins on x64 except Flash and Silverlight

**Comment by wolfbeast** [comment]
Do you know when exactly this blacklisting occurred?

**Comment by ianamk** [comment]
as far as I know always the official x64 bit Firefox builds never allowed for npapi plugins other then flash and silverlight
I believe it was way back in Firefox 43
https://blog.mozilla.org/futurereleases/2015/12/15/firefox-64-bit-for-windows-available/
from
https://wiki.mozilla.org/Firefox/Win64#Schedule
 2015 Q4

    [DONE] October 8 - Announced NPAPI to be removed by end of 2016: NPAPI Plugins in Firefox
    [DONE] December 15 - Firefox 43: Release 64-bit Firefox builds

**Comment by wolfbeast** [comment]
All right. Time for that whitelist to go. Special treatment for vendors that have agreements with Mozilla doesn't belong in UXP.
