### ISSUE TITLE
Remove GC ZEAL Spidermonkey debug code.

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/moebius#21]
GC_Zeal is a mechanism to split up or increase the frequency of garbage collection. While this is important for troubleshooting GC issues in SpiderMonkey development, it is completely useless for anything else and by the looks of it, other tools have become more important since SpiderMonkey 1.8 to home in on GC issues.

GC_ZEAL has a lot of code penetration, is one of the main reasons for debug builds running like tar, and uses some run-time controls to change GC methods (enabling/disabling GGC, for example) which may leave runtimes in undesirable states, as well. Removing this will greatly simplify a lot of code.

**Comment by mattatobin** [comment]
http://xref.palemoon.org/moebius-trunk/search?string=JS_GC_ZEAL

**Comment by mattatobin** [comment]
I have given this a build and it compiled successfully on x86. I also ran the full suite of Dromaeo tests.. Not for benchmarks but as a stability test for spidermonkey. Seems to be A-OK.

If anyone is interested here are the results of that test: http://dromaeo.com/?id=266137

**Comment by wolfbeast** [comment]
Thanks for the build and test. Merging.
