### ISSUE TITLE
Two (and more) extensions together - http resume - basilisk crashes

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/moebius#210]
__Steps to reproduce:__
1. Install:
uBlock Origin 1.14.18
BetterStop 1.0.1
2. Open http://sagamusix.untergrund.net/fileupload.htm.
3. Select a small file and hit the submit button.

__Actual results:__
Basilisk crashes when trying to upload the file. Trying to upload to the same domain as the HTML file resides on interestingly does not trigger the crash, nor when opening the file from the file:// protocol.

__Expected results:__
Basilisk should certainly not crash when trying to submit a form.

**Comment by mattatobin** [comment]
Have you verified this indeed happens because your bugzilla copypasta with firefox substituted with basilisk is not reassuring.

**Comment by janekptacijarabaci** [comment]
> Have you verified this indeed happens

Of course.
