### ISSUE TITLE
Manual check for add-on updates doesn't find CTR version 1.7.3.4

### ISSUE THREAD

**Issue by Telmesomething** [MoonchildProductions/moebius#214]
Running a manual check for updates doesn't find CTR version 1.7.3.4 released November 29, 2017. 

It does appear in the list when running a manual check on Firefox ESR 52.5. The attached screenshot came from there. 

![ctr1734](https://user-images.githubusercontent.com/33827636/33428713-3c352e36-d5ca-11e7-8357-f0ce84fa3b5b.PNG)

**Comment by JustOff** [comment]
Add-ons update does not work in Basilisk at the moment (see #189), this will be fixed in the upcoming release.

**Comment by Telmesomething** [comment]
After updating to the latest version of Basilisk today, the problem appears to persist although in a different way. Instead of finding the latest CTR version at https://addons.mozilla.org/en-US/firefox/addon/classicthemerestorer/versions/ 
it finds the latest beta instead: https://addons.mozilla.org/en-US/firefox/addon/classicthemerestorer/versions/beta?page=1#version-1.7.3.2beta1

Here's a pix of it as it appears in the addons manager: 

![ctr1734beta1](https://user-images.githubusercontent.com/33827636/33488198-3424b0cc-d6b0-11e7-96db-5cda86647279.PNG)

**Comment by JustOff** [comment]
> it finds the latest beta instead

It will find beta if you have beta installed and vice versa.

**Comment by Telmesomething** [comment]
> It will find beta if you have beta installed and vice versa.

OK, understand. I downloaded it directly from the AMO site instead.
