### ISSUE TITLE
about:license needs fixing... 

### ISSUE THREAD

**Issue by Vangelis66** [MoonchildProductions/moebius#222]
It starts by 

`Binaries of this product have been made available to you by the Mozilla Project` 

I propose it gets changed to 

`Binaries of this product have been made available to you by Moonchild Productions`

(BTW, `Mozilla Project` also links to `http://www.mozilla.org/`, so the link should change, too...)

**Comment by wolfbeast** [comment]
Yup, that needs deMOZifying. `about:rights` also needs to have placeholder text filled in.
