### ISSUE TITLE
Basilisk vs. Firefox (in strings, file names...)

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/moebius#227]
The change of the application name - in strings, file names...

See also:
`firefox.js`
`firefox-branding.js`
`firefox-l10n.js`
`FirefoxBranding()`
`firefox.ico`
`firefox.icns`

**Comment by janekptacijarabaci** [comment]
@wolfbeast 
If you want to (#237, #241), please let me know.

**Comment by wolfbeast** [comment]
Would be nice to have on UXP. Sorry for not giving this proper attention before. 
Closing on this repo as prep for archiving.

**Comment by janekptacijarabaci** [comment]
I don't mind. I'll look at it later...
