### ISSUE TITLE
Internal Updater fails on Windows 32bit OSes

### ISSUE THREAD

**Issue by Vangelis66** [MoonchildProductions/moebius#229]
OS: Win7 SP1 32bit, fully updated
Basilisk: win32 (obviously...)
full version string="55.0.2017.11.12" (consistent with what is reported inside "about:" internal page)
truncated version string="2017.11.12" {this is reported inside "about:support" internal page and also printed inside the "About Basilisk" popup window [actually it's "2017.11.12 (32-bit)" in that one...]}

The [Release Notes](https://www.basilisk-browser.org/releasenotes.shtml) page (accessible via the "What's new" link in aforementioned popup) informs of a new update (v**2017.12.01**), however the "About Basilisk" popup tells me that "_**Basilisk is up to date**_". 

I first did my own troubleshooting via `Tools => Web Developer => Web Console`, here are some screenshots: 

![headers](https://user-images.githubusercontent.com/9669492/33800260-f58d30fa-dd44-11e7-87b4-05954f58e911.jpg)

![parameters](https://user-images.githubusercontent.com/9669492/33800261-ff1c1ffa-dd44-11e7-8ae9-4953d0323f68.jpg)

I then browsed the "PM Forums/Bk subforum" to check whether anything related had cropped up and I stumbled upon [this](https://forum.palemoon.org/viewtopic.php?f=61&t=17613) thread; I followed the debugging procedure indicated there (toggle pref `app.update.log` and check Browser Console output), here comes the result: 
```
05:17:20.919 AUS:SVC Checker: checkForUpdates, force: true
05:17:20.923 AUS:SVC Checker:getUpdateURL - update URL: https://aus.basilisk-browser.org/?application=Basilisk&version=55.0.2017.11.12&arch=WINNT_x86-msvc-x86&buildid=20171112122043&channel=release&force=1
05:17:20.924 AUS:SVC Checker:checkForUpdates - sending request to: https://aus.basilisk-browser.org/?application=Basilisk&version=55.0.2017.11.12&arch=WINNT_x86-msvc-x86&buildid=20171112122043&channel=release&force=1
05:17:20.917 GET 
XHR 
https://aus.basilisk-browser.org/ [HTTP/2.0 200 OK 122ms]
05:17:21.106 AUS:SVC Checker:onLoad - request completed downloading document
05:17:21.106 AUS:SVC Checker:onLoad - number of updates available: 0
```
Indeed, when I load in a tab `https://aus.basilisk-browser.org/?application=Basilisk&version=55.0.2017.11.12&arch=WINNT_x86-msvc-x86&buildid=20171112122043&channel=release&force=1` I get no updates: 
```xml
<updates> </updates>
```
My sister owns a Win7 SP1 64bit laptop, which I borrowed to conduct further tests; the win32 Basilisk version there (on a x64 OS) composes the following update URL 
`https://aus.basilisk-browser.org/?application=Basilisk&version=55.0.2017.11.12&arch=WINNT_x86-msvc-x64&buildid=20171112122043&channel=release&force=1` which **does** produce a valid response: 
```xml
<updates><update type="major" displayVersion="2017.12.01" appVersion="55.0.2017.12.01" extensionVersion="55.0.2017.12.01" buildID="20171201092741" detailsURL="http://www.basilisk-browser.org/"><patch type="complete" URL="http://aus.basilisk-browser.org/release/basilisk-20171201092741.en-US.win32.complete.mar" hashFunction="SHA256" hashValue="8a1ce853c3843ab1af0081ba0a2855027d3318d70116048aaad1d4dab48f870b" size="51039616"/></update></updates>
```
Likewise, the x64 version of Basilisk there composes the following update URL: 
`https://aus.basilisk-browser.org/?application=Basilisk&version=55.0.2017.11.12&arch=WINNT_x86_64-msvc-x64&buildid=20171112123433&channel=release&force=1` and the server does respond with an update: 
```xml
<updates><update type="major" displayVersion="2017.12.01" appVersion="55.0.2017.12.01" extensionVersion="55.0.2017.12.01" buildID="20171201110639" detailsURL="http://www.basilisk-browser.org/"><patch type="complete" URL="http://aus.basilisk-browser.org/release/basilisk-20171201110639.en-US.win64.complete.mar" hashFunction="SHA256" hashValue="ec1f989ab33380819d8a4bead641bc1c6b60c6f1b215fa15fcd1a34f927e8d35" size="58605903"/></update></updates>
```
So, the issue lies only with Basilisk-win32 updates on a x86 Windows architecture... I did some poking around with the update URL on my setup, it would appear that a valid URL accepted by the update server is: 
`https://aus.basilisk-browser.org/?application=Basilisk&version=55.0.2017.11.12&arch=WINNT_x86-msvc&buildid=20171112122043&channel=release&force=1` => 
```xml
<updates><update type="major" displayVersion="2017.12.01" appVersion="55.0.2017.12.01" extensionVersion="55.0.2017.12.01" buildID="20171201092741" detailsURL="http://www.basilisk-browser.org/"><patch type="complete" URL="http://aus.basilisk-browser.org/release/basilisk-20171201092741.en-US.win32.complete.mar" hashFunction="SHA256" hashValue="8a1ce853c3843ab1af0081ba0a2855027d3318d70116048aaad1d4dab48f870b" size="51039616"/></update></updates>
```
So, either 1) the win32 version on Win x86 has to be patched in order to compose the above URL when checking for updates or 2) the update server has to be patched to provide a valid response to the update request (`https://aus.basilisk-browser.org/?application=Basilisk&version=55.0.2017.11.12&arch=WINNT_x86-msvc-x86&buildid=20171112122043&channel=release&force=1`) sent currently... 

I hope I have provided enough info towards the resolution of this bug; thanks for your time and attention 😃

**Comment by wolfbeast** [comment]
You provided more information than needed :)
The issue was your architecture string. Basilisk adds an extra -x86 or -x64 to it, which I assumed was a build-time string but apparently it's part build-time and part runtime, where x86 or -x64 designates the native bitness of the OS the browser is run on. That needed an extra entry in the automatic update script (which has now been done).

If all is well, it should now serve you the update (due to caching it may take an hour or two before it has propagated completely server-side).

**Comment by Vangelis66** [comment]
> If all is well, it should now serve you the update

Indeed, I can confirm this: 

![about_basilisk](https://user-images.githubusercontent.com/9669492/33844495-21e8910c-dea9-11e7-926e-7c7e17834ee8.jpg)
![ab_mar-downloading](https://user-images.githubusercontent.com/9669492/33844518-2ea1a906-dea9-11e7-943d-1303e56ab45a.jpg)

Many thanks for the fix 👍 ; I'll be closing this now...
