### ISSUE TITLE
Drop an Atomic Bomb on Windows Maintenance Service

### ISSUE THREAD

**Issue by mattatobin** [MoonchildProductions/moebius#23]
We have tried fire and acid and it keeps coming back.. Time to pull out that ol' 1952 special.

----

_LAST TIME ON MOZ_MAINTENANCE_SERVICE_

https://github.com/MoonchildProductions/Pale-Moon/commit/4c7fc4f188e52e365ca3323c55cb0499b34ce89a
https://github.com/MoonchildProductions/Pale-Moon/commit/83044bbb69c7d48e5fb9679622062f27eeb9169b
https://github.com/MoonchildProductions/Pale-Moon/commit/e3299799b1ed4b741a562b5499248be24ce9ddea
https://github.com/MoonchildProductions/Pale-Moon/commit/dd88f4376e7f0675247480c3608293c4e065946f

----

- [ ] Remove conditional MOZ_MAINTENANCE_SERVICE code
http://xref.palemoon.org/moebius-trunk/search?string=MOZ_MAINTENANCE_SERVICE
- [ ] `toolkit/mozapps/update/nsUpdateService.js`
`isServiceInstalled`
`useService`
`shouldUseService`
- [ ] Non ifdef'd code from `toolkit/mozapps/updater/updater.cpp`
- [ ] Remove `toolkit/components/maintenanceservice/`
- [ ] `Basilisk` Windows Installer

**Comment by wolfbeast** [comment]
Please only use the "Basilisk" tag for front-end/application issues.

**Comment by mattatobin** [comment]
This affects code IN basilisk.. Specifically the installer..
