### ISSUE TITLE
Addons - Can't install some addons

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/moebius#238]
Ad: https://forum.palemoon.org/viewtopic.php?f=61&t=17664

> I can't install some legacy Firefox addons like this:
https://addons.mozilla.org/it/firefox/addon/poper-blocker-pop-up-blocker/
https://addons.mozilla.org/cs/firefox/addon/wappalyzer/

> I can install that addon on Firefox version 48+, Waterfox, but on Basilisk I get this error:
![cannot-be-installed](https://user-images.githubusercontent.com/2373486/33872077-a6ecd248-df15-11e7-9ebb-ccd72cb88259.png)

and throws an error in Browser Console:
```
addons.xpi WARN
Download of https://addons.mozilla.org/....xpi?src=dp-btn-primary failed:
Error: Cannot find id for addon [drive]:\[path]\Temp\tmp-lho.xpi
(resource://gre/modules/addons/XPIProvider.jsm:5490:19)
JS Stack trace: loadManifest/<@XPIProvider.jsm:5490:19
< TaskImpl_run@Task.jsm:319:42
< process@Promise-backend.js:917:23
< walkerLoop@Promise-backend.js:801:7
< scheduleWalkerLoop/<@Promise-backend.js:737:11
```

---

See:
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/WebExtensions_and_the_Add-on_ID#When_do_you_need_an_Add-on_ID
https://bugzilla.mozilla.org/show_bug.cgi?id=1284407

---

My suggestion for correction would be:
https://github.com/janekptacijarabaci/moebius/tree/_testBranch_addons_id_1

**Comment by JustOff** [comment]
I think [here](https://github.com/JustOff/moebius/commit/68a6d54781dd58eafc839392c5881cdf672b2f45) is more accurate solution.

**Comment by mattatobin** [comment]
I thought we had id-less webex support at our level.. If not.. It needs to be backported..

**Comment by janekptacijarabaci** [comment]
@JustOff 

Ad:
``` javascript
-    if (!addon.id && aInstallLocation == TemporaryInstallLocation) {
+    if (!addon.id) {
       addon.id = generateTemporaryInstallID(aZipReader.file);
     }
```

IMHO:
There is a problem with name files, multiple installations and updates using the temporary ID (always different!)...

__Installations:__
The first time: `5c1b8087b55409463fba4f21d9a54c142d6685ec@temporary-addon.xpi`
The second time: `92c07d339b22266193c9d1d7eafea5dcbb4368e6@temporary-addon.xpi`
etc.

__Updating__ (e.g. https://addons.mozilla.org/cs/firefox/addon/wappalyzer/):
```
addons.update-checker	WARN
Update manifest for 5c1b8087b55409463fba4f21d9a54c142d6685ec@temporary-addon
did not contain an updates property
```

**Comment by JustOff** [comment]
@janekptacijarabaci 

Well, you're right, I missed this point. But what about unsigned add-ons without id?

**Comment by janekptacijarabaci** [comment]
> But what about unsigned add-ons without id?

Yes. I have no solution (it does not work even in FF56 - a last nightly).
