### ISSUE TITLE
Remove SystemAddons from XPIprovider

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/moebius#239]
What it says on the tin. There's no need for us to ever push hidden extensions to browser users like Mozilla does.

Blocks #66

**Comment by wolfbeast** [comment]
Cautionary warning: the default theme is a system add-on; this should probably be be converted first.

**Comment by mattatobin** [comment]
It's been largely de-fanged here.. Full removal will happen in `Take 2`
