### ISSUE TITLE
Restore the Toolkit Error Console

### ISSUE THREAD

**Issue by mattatobin** [MoonchildProductions/moebius#246]
The Toolkit Error Console aka the old jsconsole is important for platform development as it is an application independent component.

I am planning to effectively revert https://github.com/mozilla/gecko-dev/commit/1adf4b4140ec74eda31a8e137ba515c0ddefda57 (Mozilla Bug 1278368)

**Comment by mattatobin** [comment]
I have the files restored and the build system and jar manifests hooked back up.
The -jsconsole command line argument works

Next, I will want to restore the menu item to Basilisk.

In the meantime, @trav90 could you build from my branch @ https://github.com/binoc-central/moebius-contrib/tree/jsconsole-work

Ensure the command line argument works and the skin for Linux is correct?

**Comment by mattatobin** [comment]
Menu Item restored though it is the first item on the web developer menu.. This ordering can be fixed later.. maybe..

**Comment by trav90** [comment]
Confirmed builds and -jsconsole argument works:

![image](https://user-images.githubusercontent.com/10595410/34185174-7cc88262-e4e9-11e7-8071-3fdde6d273d9.png)
