### ISSUE TITLE
Developer Tools do not work on Linux

### ISSUE THREAD

**Issue by JustOff** [MoonchildProductions/moebius#252]
Ctrl+Shift+K displays empty box, Ctrl+Shift+J does not show anything and I can't change filters.

Tested using Ubuntu 14.04 and Mint 18 with a clean profile.

See also: https://forum.palemoon.org/viewtopic.php?p=130462#p130462

**Comment by janekptacijarabaci** [comment]
Dupe of #197

**Comment by JustOff** [comment]
Oops, I missed that somehow.
