### ISSUE TITLE
Basilisk 2017.12.03 [GNU/Linux]: Suggestion - Restore "Recently Bookmarked" smart bookmarks folder

### ISSUE THREAD

**Issue by KNTRO** [MoonchildProductions/moebius#253]
This smart bookmarks folder can't be used.

![Recently Bookmarked smart bookmarks folder grayed out](https://user-images.githubusercontent.com/2568821/34183097-d904c2ee-e4f7-11e7-8ed0-262cb41dcf96.png)

**Comment by janekptacijarabaci** [comment]
This is the title, not a submenu. See https://bugzilla.mozilla.org/show_bug.cgi?id=1219804

**Comment by KNTRO** [comment]
@janekptacijarabaci I see.

So, what about to create a smart bookmarks folder with `place:queryType=1&sort=8&maxResults=10` as URI? _Recently Bookmarked_ used to be this kind of folder.

I did it for myself [_Marcadores recientes_], but it would be useful to have enabled for all users.
![Some smart bookmarks folders](https://user-images.githubusercontent.com/2568821/34200673-b0653db0-e550-11e7-86d5-d74b7fd712cd.png)

**Comment by wolfbeast** [comment]
It's a change made on purpose.
![attachment](https://user-images.githubusercontent.com/3359132/34228836-6f28bd36-e5d2-11e7-9103-d0a368473627.png)

**Comment by KNTRO** [comment]
@wolfbeast Oh, got it. Thanks for letting me know this. 🆗

OK, case closed.
