### ISSUE TITLE
DevTools - add support for -browserconsole (the command line)

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/moebius#254]
__Actual results:__
`-jsconsole` (the Error Console)

__Expected results:__
`-jsconsole` (the Error Console)
`-browserconsole` (the Browser Console)

See also:
https://github.com/MoonchildProductions/Pale-Moon/pull/1019#issuecomment-318881525

**Comment by mattatobin** [comment]
Why do we need to invoke the devtools from command line? We have the toolkit error console back.

**Comment by janekptacijarabaci** [comment]
People want to have more choice (including me). Both things are different - and have different uses.

**Comment by mattatobin** [comment]
There is no usecase in my opinion that the very breakable devtools require a command line argument that isn't covered by a stable and undependent component like the jsconsole.

**Comment by janekptacijarabaci** [comment]
So backward compatibility (with PM) will not be maintained and this result (with `-help`) makes no sense:
```
  --jsconsole                     Open the Error console.
...
  --jsconsole                     Open the Browser Console.
```

We have a completely different view...
I don't see the reason to run the Error Console, if the browser / devtools / web/browser console works (and starts correctly).

**Comment by janekptacijarabaci** [comment]
> What users other than yourself have requested this?

> Are you going to ensure not building with devtools will not cause an issue?

No, I don't plan (rather) anything at all, especially long... term (with Pale Moon / Basilisk).

**Comment by mattatobin** [comment]
There is no way to use devtools if the application in question is busted or devtools is busted or jetpack/webex is busted (whichever this incarnation uses).. The Toolkit Console on the other hand is an essential development aid.

Your obsession with failing fragile/half-broken Mozilla contrivences of the 2010s will be the death of this project JUST as it is at MozCo.

This backwards compatibility aspect is of your oen creation substantiated merely by some random bugzilla number.

You continue to never talk about let alone justify anything you do or ask before hand as I do and the bulk of your so-called fixes almost always leads to incomplete follow ups that has done nothing in my view but create noise and instability of untrackable changes without explaination. Have we not had enough of that from Mozilla?

**Comment by mattatobin** [comment]
The fact is.. I don't know how much longer I can stand having to keep track of the big picture to contine to keep people from doing things to satisfy their own selfish goals when there is so much more important things to accomplish that keeps these codebases from falling into the Mozilla pattern of missing the point and short term gains sacrafising the future without even considering the wider effects and implications of what ever change that happens.

**Comment by janekptacijarabaci** [comment]
> Ad: No, I don't plan (rather) anything at all, especially long... term (with Pale Moon / Basilisk).

...it is precisely for that reason.

**Comment by mattatobin** [comment]
Explain what that means..

Because from my chair it looks much like "I want something, damn the consequence.. Not like I am gonna be around to fix it."

I have been rarely wrong in the past and have come to cherish when I am because everything I am right about for some time has been something terrible...

**Comment by mattatobin** [comment]
Right.. Enough meta.. Please ensure functioning and behavior of this cli argument with all three devtools configure states.

**Comment by janekptacijarabaci** [comment]
`MOZ_DEVTOOLS=all`

`-help`:

```
  -h or --help                                 Print this message.
  -v or --version                              Print Basilisk version.
  -P <profile>                                 Start with <profile>.
  --profile <path>                             Start with profile at <path>.
  --migration                                  Start with migration wizard.
  --ProfileManager                             Start with ProfileManager.
  --no-remote                                  Do not accept or send remote commands;
                                               implies --new-instance.
  --new-instance                               Open new instance, not a new window
                                               in running instance.
  --UILocale <locale>                          Start with <locale> resources as UI Locale.
  --safe-mode                                  Disables extensions and themes for this session.
  --console                                    Start Basilisk with a debugging console.
  --jsconsole                                  Open the Error console.
  --browser                                    Open a browser window.
  --new-window <url>                           Open <url> in a new window.
  --new-tab <url>                              Open <url> in a new tab.
  --private-window <url>                       Open <url> in a new private window.
  --preferences                                Open Options dialog.
  --search <term>                              Search <term> with your default search engine.
  --browserconsole                             Open the Browser Console.
  --jsdebugger                                 Open the Browser Toolbox.
  --devtools                                   Open DevTools on initial load.
  --start-debugger-server [ws:][<port>|<path>] Start the debugger server on
                                               a TCP port or Unix domain socket path.
                                               Defaults to TCP port 6000.
                                               Use WebSocket protocol if ws: prefix
                                               is specified.
  --recording <file>                           Record drawing for a given URL.
  --recording-output <file>                    Specify destination file for a drawing recording.
  --setDefaultBrowser                          Set this app as the default browser.
```

- `-jsonsole`
   - works
- `-browserconsole`
   - works

---

`MOZ_DEVTOOLS=`

__Package bustage:__
```
Error: [drive]:\[path]\browser\installer\package-manifest.in:374: Missing file(s): bin/browser/components/devtools-startup.manifest
Error: [drive]:\[path]\browser\installer\package-manifest.in:375: Missing file(s): bin/browser/components/devtools-startup.js
Error: [drive]:\[path]\browser\installer\package-manifest.in:376: Missing file(s): bin/browser/components/webideCli.js
Error: [drive]:\[path]\browser\installer\package-manifest.in:377: Missing file(s): bin/browser/components/webideComponents.manifest
Error: [drive]:\[path]\browser\installer\package-manifest.in:615: Missing file(s): bin/browser/chrome/webide
Error: [drive]:\[path]\browser\installer\package-manifest.in:616: Missing file(s): bin/browser/chrome/webide.manifest
Error: [drive]:\[path]\browser\installer\package-manifest.in:617: Missing file(s): bin/browser/defaults/preferences/webide-prefs.js
Error: [drive]:\[path]\browser\installer\package-manifest.in:622: Missing file(s): bin/browser/defaults/preferences/devtools.js

mozmake.EXE[4]: *** ../../devtools/client/locales: No such file or directory.  Stop.
mozmake.EXE[4]: Leaving directory '[drive]:/[path]/browser/locales'
mozmake.EXE[3]: *** [Makefile:109: libs-en-US] Error 2
mozmake.EXE[3]: Leaving directory '[drive]:/[path]/browser/locales'
mozmake.EXE[2]: *** [Makefile:162: libs] Error 2
mozmake.EXE[2]: Leaving directory '[drive]:/[path]/browser/installer'
mozmake.EXE[1]: *** [[drive]:/[path]/config/rules.mk:522: default] Error 2
mozmake.EXE[1]: Leaving directory '[drive]:/[path]/browser/installer'
mozmake.EXE: *** [[drive]:/[path]/browser/build.mk:9: package] Error 2
mozmake.EXE: Leaving directory '[drive]:/[path]/'
```

Fixed (temporary) for `browser/installer/package-manifest.in`:
`#ifdef MOZ_DEVTOOLS` - lines: 374-377, 622

`-help`:

```
  -h or --help                                 Print this message.
  -v or --version                              Print Basilisk version.
  -P <profile>                                 Start with <profile>.
  --profile <path>                             Start with profile at <path>.
  --migration                                  Start with migration wizard.
  --ProfileManager                             Start with ProfileManager.
  --no-remote                                  Do not accept or send remote commands;
                                               implies --new-instance.
  --new-instance                               Open new instance, not a new window
                                               in running instance.
  --UILocale <locale>                          Start with <locale> resources as UI Locale.
  --safe-mode                                  Disables extensions and themes for this session.
  --console                                    Start Basilisk with a debugging console.
  --jsconsole                                  Open the Error console.
  --browser                                    Open a browser window.
  --new-window <url>                           Open <url> in a new window.
  --new-tab <url>                              Open <url> in a new tab.
  --private-window <url>                       Open <url> in a new private window.
  --preferences                                Open Options dialog.
  --search <term>                              Search <term> with your default search engine.
  --recording <file>                           Record drawing for a given URL.
  --recording-output <file>                    Specify destination file for a drawing recording.
  --setDefaultBrowser                          Set this app as the default browser.
```

- `-jsonsole`
   - works (but there are several errors, because missing DevTools - and it is not solved)

- `-browserconsole`
   - throws (so it's OK):
     _Error:_
     _Warning: unrecognized command line flag -browserconsole_
     _Source_
     _File: resource://app/components/nsBrowserContentHandler.js_
     _Line: 727_

---

IMHO/AFAIK: There is no difference before and after enabling this PR.

---

> there is so much more important things to accomplish

(I skipped `their own selfish goals`... - for obvious reason)

In that case I wish good luck to other developers (and users) to find (and add) (much) more important things...

I have much more important things to work. Also.

**Comment by mattatobin** [comment]
Alright, guess it is as good as it can be given the application not accounting for lack of devtools. Thanks for checking..

I am fine with this being added then.
