### ISSUE TITLE
Vimeo support

### ISSUE THREAD

**Issue by szepeviktor** [MoonchildProductions/moebius#258]
Could it be possible that Vimeo.com does not play (no browser console messages) in Basilisk 2017.12.01 64-bit on W10 Pro 64-bit?

**Comment by wolfbeast** [comment]
I don't see why it wouldn't.

**Comment by wolfbeast** [comment]
Just tested x64 on W7, no problem.

**Comment by szepeviktor** [comment]
Now it does.

Maybe it was Vimeo issue.
