### ISSUE TITLE
Deal with FIREFOX_VERSION and redundent FIREFOX/MOZ_APP_VERSION_DISPLAY

### ISSUE THREAD

**Issue by mattatobin** [MoonchildProductions/moebius#26]
For some strange reason Mozilla loves to tie the version of applications into the top level build system and also has more recently implemented a display or pretty version number. This is not desirable as it causes version ambiguity and confusion and makes the codebase less flexible.

As with Tycho least in part.. Basilisk will return to defining MOZ_APP_VERSION directly and within the scope of its application tree.

Mobile should also be sync'd to this behavior.

---
http://xref.palemoon.org/moebius-trunk/search?string=FIREFOX_VERSION
http://xref.palemoon.org/moebius-trunk/search?string=MOZ_APP_VERSION_DISPLAY

**Comment by wolfbeast** [comment]
Can you move forward with this please? it's blocking my development.

**Comment by mattatobin** [comment]
I am still ill so for now just keep versons sync'd until I can get to it...

**Comment by wolfbeast** [comment]
All right, I'll just use what I have available and clear the milestone.

**Comment by wolfbeast** [comment]
I have to say I like being able to have a separate display version, so we can use Firefox's version for Basilisk in sync with what the web wants, while starting with 1.0 for the user..

**Comment by wolfbeast** [comment]
A different solution was chosen for this and implemented. closing.
