### ISSUE TITLE
No MD5SUMS or SHA256 in download page

### ISSUE THREAD

**Issue by NikTh** [MoonchildProductions/moebius#260]
I went [here](https://www.basilisk-browser.org/download.shtml) to download Basilisk. I saw three alternative mirrors. I downloaded Basilisk from the EU mirror, a site without any security (HTTPS). 

How do I know that the file is not corrupted, modified or anything else ? 
How do I know that it is actually the file you (the developers) created ? 

Please add the relevant MD5SUMS and SHA256SUMS in download page. 
Even better, also add the MD5SUMS.gpg and SHA256SUMS.gpg

So anyone can verify the integrity and authenticity of what downloads.

**Comment by wolfbeast** [comment]
Adding checksums should suffice, considering the download page is available over https (so cannot be forged). https for file downloads and pgp signatures of checksum files are unnecessary. 

It will just take some batch mangling to generate these in the publishing step.
