### ISSUE TITLE
Tabmix Plus + Basilisk = no multi-row tabs = 101% shit - browser needed to be uninstalled forever

### ISSUE THREAD

**Issue by C0MPAQ** [MoonchildProductions/moebius#263]
Basilisk 2017.12.03 (64-bit)
Tab Mix Plus 0.5.0.4

(both are kind of just the latest stuff)

As soon as the tabs start hitting the second row, its just not displayed. The tabs disappear into a void and the address bar remains static.

Status: beyond critical - browser is unusable without multi-row tabs.

**Comment by wolfbeast** [comment]
Take your own advice then and uninstall the browser, and stop opening issues on a product you're not using for incompatibilities that need to be solved by extensions authors.
Basilisk != Firefox.
