### ISSUE TITLE
Publish intermediate version

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/moebius#266]
Not exactly the next milestone because a few more things need addressing, but it's probably a good idea to publish an intermediate dev version in the next couple days, @trav90 -- Could you make a build of the release branch today?

**Comment by wolfbeast** [comment]
Release notes:

- Fixed several compatibility issues with WebExtensions.
- Disabled Mozilla's "system add-ons" service, which would allow Mozilla to remotely install add-ons.
- Disabled Mozilla's "system settings" service, which would allow Mozilla to remotely change settings or block add-ons.
- Updated SQLite lib to 3.21.0.
- Added an option to block top-level `data:` URIs.
- Removed referrers when opening links in new private windows.
- Updated license and rights pages.
- Changed the Feedback link to point to the forum instead of Mozilla.
- Fixed an issue with exportFunction().
- Fixed/enabled the use of Firefox Sync (Firefox Accounts).
- Restored the toolkit Error Console for application troubleshooting.
- Added `-jsconsole` and `-browserconsole` command-line arguments for launching of either console on startup.
- Removed what was left of the underused Social API.
- Changed the way element border rounding is done in Goanna to have natural rounding up/down of fractional sizes (IEEE 754).
- Fixed a potential leak involving IndexedDB and private browsing mode.
- Fixed a crash in ANGLE.

**Comment by trav90** [comment]
I'll make a build as soon as I get home this evening.

**Comment by wolfbeast** [comment]
Thank you!

**Comment by trav90** [comment]
Signed, release-ready tarball is uploading to the FTP site as I post this.

**Comment by wolfbeast** [comment]
Published.
