### ISSUE TITLE
Incorrect Browser Registration on Windows

### ISSUE THREAD

**Issue by jdunn0** [MoonchildProductions/moebius#271]
On Windows, the Firefox installer uses the HKCR\FirefoxHTML and HKCR\FirefoxURL registry keys to create associations that are using when setting browser defaults.
The Palemoon installer uses HKCR\PalemoonHTML and HKCR\PalemoonURL registry keys
The Basilisk installer should use should something like HKCR\BasiliskHTML and HKCR\BasiliskURL as registry keys but it currently uses the same registry keys as the Firefox installer.
There are other keys involved in the browser registration but that should be enough information to figure all what all needs to be changed.
If not, I listed the required registry keys in my [Reddit Post](https://www.reddit.com/r/waterfox/comments/3xrupj/waterfox_is_being_incorrectly_registered_as_a/) regarding the same [issue for Waterfox](https://github.com/MrAlex94/Waterfox/issues/343).

As it appears moebius is a codebase that Basilisk is based off that is intended for use other then Basilisk, this might be issue that needs to be fixed in moebius so that Basilisk and any other future projects using the moebius codebase don't have this issue.

**Comment by wolfbeast** [comment]
This is controlled/set by the application-specific installer, not by the platform. It can't be addressed on the platform side.
However, it's a good point and should be fixed in the installer for Basilisk to prevent collisions.

**Comment by jdunn0** [comment]
It's not just an installer issue because when the browser is run, it has code to check for and set the default browser if the user wants too.
Just a quick search of this repository for FirefoxHTML shows the file "moebius/browser/components/shell/nsWindowsShellService.cpp" has references to FirefoxHTML.
Besides dealing setting the default browser if a user wants to, it appears to contain code to handle functions available in the [Set Program Access and Computer Defaults](https://msdn.microsoft.com/en-us/library/windows/desktop/cc144162(v=vs.85).aspx) section of Add/Remove remove programs added in Windows XP SP2 (Which appears to have been removed the latest version of Windows 10).

**Comment by mattatobin** [comment]
That's true thanks for reminding us about shellservice.

**Comment by wolfbeast** [comment]
I did look in the shellservice C++ when I worked on this, but didn't see anything hard-coded in the obvious places to look and assumed it was picked up from globals; I should have been more thorough, because apparently it is not and locally parameterized instead.

Even so, that's still application and not platform code.

**Comment by wolfbeast** [comment]
Did I miss anything else?

**Comment by mattatobin** [comment]
Installer and ShellService should be it..
