### ISSUE TITLE
Release an extra intermediate release to mitigate HW-timing attacks.

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/moebius#274]
Basilisk didn't get Pale Moon's treatment yet of a courser performance timer cap. As such, it's still at 5 us in released version which isn't course enough to mitigate Meltdown and Spectre attacks.
9dbab891152ea9b3affd97ea567b7c392fc0563c  fixes this, and we should release a build with this patch asap. Merged to release and tagged; @trav90 please make a Linux build on 2018-01-05 00:00UTC or later to make sure the version matches the tag. I'll publish tomorrow.

**Comment by trav90** [comment]
Will do.

**Comment by wolfbeast** [comment]
Didn't push the commits yet but they should be on GitHub now.

**Comment by trav90** [comment]
Yup see them now. Will kick off a build in a few minutes (looks like we're right at 00:00 UTC now).

**Comment by wolfbeast** [comment]
Sorry, you'll have to interrupt and rebuild -- I missed one pref that should have been saved in all.js but I didn't hit the save button. :P I'll move the tag accordingly.

**Comment by wolfbeast** [comment]
Updated.

**Comment by trav90** [comment]
Heh, the build completed and I was just about to upload to FTP. No problem though; kicking off a new build now. :+1:

**Comment by trav90** [comment]
Signed tarball with all the goodies is uploaded to FTP.

**Comment by wolfbeast** [comment]
Published 2018-01-05 @09:00 UTC, give or take 15 minutes to propagate to the mirrors.
