### ISSUE TITLE
Exclude default theme from update checks

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/moebius#275]
For some reason (probably to get a ping from Firefox installations that don't have extensions or themes installed) Mozilla treats the default theme as something to include in extension update checks.

This is pointless, and causes unnecessary traffic. We need to exclude this from update checks completely.
ID is  `{972ce4c6-7e08-4474-a285-3208198ce6fd}`.

**Comment by mattatobin** [comment]
In UXP it seems this is counted as a System Add-ons so it MAY be taken care of when System Add-ons framework goes.

Though, it may just fall back to normal AUS as well..
