### ISSUE TITLE
Unable to compile on Linux Mint (debug build)

### ISSUE THREAD

**Issue by Max-E** [MoonchildProductions/moebius#276]
OS: 64-bit Linux Mint 18 Sarah (corresponding to Ubuntu 16.04)

Versions tried: 
* A snapshot of master (Git hash 51f6d75ab418ea5d3674ea145912eb65caba6d6f)
* The v2018.01.05 tag

Compile process used:
* Installed all dependencies listed here https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Build_Instructions/Simple_Firefox_build/Linux_and_MacOS_build_preparation
* Added the following line to mozconfig to enable debugging symbols: `ac_add_options --enable-debug`
* Ran the command `./mach build`

I have never compiled Firefox before, but that is the process that seems to be recommended. If Basilisk requires a different process, I couldn't find that in the readme.

Compile output for v2018.01.05: https://pastebin.com/rnB4Sb0f
Compile output for master snapshot: https://pastebin.com/h8rskGwR
Please let me know if you want any of the auto-generated makefiles, etc.

I did master first, and then the tag, and I did not do any form of `make clean` or equivalent action between attempts.

**Comment by wolfbeast** [comment]
`--enable-debug` does not "enable debugging symbols", it builds a totally different `debug build`. You normally don't need a debug build unless you very specifically need to troubleshoot something that needs extremely extensive logging and checking of everything.

Obviously there's an issue with debug builds at the moment because of one assert that was added. Not using `--enable-debug` will aboid your build bustage.

**Comment by Max-E** [comment]
Ahh, it appears my google-fu has let me down. :) How do I get symbols then? Are they included by default?

**Comment by wolfbeast** [comment]
They are included by default, yes, unless you use `--disable-debug-symbols`; at least last time I checked the code base.

**Comment by wolfbeast** [comment]
It looks like debug builds are currently all sorts of broken. There's more than a few build errors involved that will need a build-fix-build-fix-etc. run to weed out.

**Comment by wolfbeast** [comment]
Closing this to re-address if needed on UXP
