### ISSUE TITLE
Fix signed extension checks

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/moebius#277]
Our checks for extension signatures has been broken for a while.

This needs to be fixed up properly, in 2 stages:

- [ ] Revert #251 and get the cert ID in a different location for WE only
- [ ] Rewrite XPIProvider's signing check parts to stop using Mozilla's hard-coded root certs and use normal libJAR signature checking

**Comment by JustOff** [comment]
> normal libJAR signature checking

Could you please give at least one example of a modern add-on that uses this type of signing and is compatible with either Pale Moon or UXP?

**Comment by mattatobin** [comment]
Anything on AMO

**Comment by JustOff** [comment]
Then, since no one actually uses libJAR compliant signatures, I honestly don't understand why not to just get rid of all this nonsense with signing. All we need is a way to get an unique id for WEs that do not have it in the manifest.

**Comment by mattatobin** [comment]
If we get rid of checking signed extensions.. People will accuse us of being insecure or ignoring security or some other dipshit conclusion.

**Comment by wolfbeast** [comment]
Update here: getting the ID-less WebExtensions to behave properly in any other way is currently not possible. XPInstaller has become incredibly fragile and will need to eventually be rewritten.
Checking author-supplied signatures is not possible any longer because Mozilla broke it a long time ago; the only signature checking that is present is against mozilla's hard-coded add-on CA certificates since the usage of NSS was removed from it.

So our current situation is:
- #251 is required for ID-less WebExtensions to work.
- Signature checking is enforced as a result, and will complain about any extensions that fail the check (meaning specifically not signed against Mozilla's certificates that in the private CertDB)
- Author-supplied JAR signatures can NOT be checked

The only reasonable solution without completely rewriting the extension installer here is to remove the warning about "not-Mozilla-signed" extensions (which includes unsigned, signed by someone else, signed-invalid) in the situation where signing is not marked as required.

We can look at if it's desirable to keep the Mozilla signing check or not; I'm leaning towards simply removing all of it, since all it can do anymore is check against the walled garden signing of Mozilla and it doesn't provide any security benefits.

**Comment by wolfbeast** [comment]
Neither of the two goals of this issue can be achieved. The warning was removed in 25384fde4edec1a003347fa4dc7d17436a003fa7 which is all we can reasonably do right now.

**Comment by JustOff** [comment]
I've been researching this issue for the last two days, so I'd like to make some corrections to the statements above:
* It's possible to get IDs for ID-less WebExtensions without using Mozilla's hard-coded root certs (I have a working code for this), so we can safely revert #251.
* With #251 reverted back and `ADDON_SIGNING = false` the author-supplied signatures verification based on NSS works just fine (I checked this using self-signed cert + CA)

If you are interested, I'm ready to fill the corresponding PR which will revert #251 + https://github.com/MoonchildProductions/moebius/commit/25384fde4edec1a003347fa4dc7d17436a003fa7 and provide the solution for ID-less WebExtensions without breaking the libJAR signature checking.

**Comment by wolfbeast** [comment]
I must have missed something in my working on this code then, because I was neither able to get IDs for ID-less WebExtensions, nor getting certs otherwise using the available tools.
If you've found a way around this, then of course I'd be interested.

**Comment by mattatobin** [comment]
This assumes that Mozilla will always use a GUID as the cert add-on id.. I am not sure that is a safe assumption.. Though, this code should work when signing its self is ripped out.. So, if it works.. Go for it.

**Comment by JustOff** [comment]
This assumption is based entirely on [Mozilla's own code](https://github.com/MoonchildProductions/moebius/blob/7ede45b5f546363ab297c66601d96252c072d36d/toolkit/mozapps/extensions/internal/XPIProvider.jsm#L1527). And yes, although I checked this myself, it would always be good to get an independent confirmation.

**Comment by JustOff** [comment]
Probably the `Wontfix` label need to be removed now.

**Comment by wolfbeast** [comment]
Partially done. It's still incomplete, though, but CBA right now. We have much more important things to worry about first.
