### ISSUE TITLE
Remove stylo

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/moebius#293]
Stylo is Servo's rust-based style system. We have a bunch of code in our tree that allows this to be enabled (experimentally). All this needs to go, since there's no intention to use Rust or Stylo or anything else servo in UXP.

**Comment by mattatobin** [comment]
http://xref.palemoon.org/moebius-trunk/search?string=MOZ_STYLO

**Comment by mattatobin** [comment]
Solved in `Take 2`
