### ISSUE TITLE
The Reader Mode - in some cases it does not work properly

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/moebius#303]
Ad:
https://forum.palemoon.org/viewtopic.php?f=61&t=18067

An example:
https://www.popsci.com/fireball-michigan-meteor-earthquake
https://eromangaweb.wordpress.com/eross-volume-1-chapter-5/
https://blog.nightly.mozilla.org/2017/04/25/guest-post-india-uses-firefox-nightly-kick-off-on-may-1-2017/

Go to `Enter Reader View`

Results:
```
Failed to load article from page
```

and throws an error in Browser Console:
```
can't access dead object ReaderMode.jsm:477
```

After applying this patch: [bug 1364056](https://bugzilla.mozilla.org/show_bug.cgi?id=1364056), the Reader Mode is working.

**Comment by mattatobin** [comment]
Go for it
