### ISSUE TITLE
X-Frame-Options: SAMEORIGIN - check traverses all ancestors, rather than just looking at "top"

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/moebius#305]
https://tools.ietf.org/html/rfc7034#section-2.3.2.2

>   To illustrate the difference between the comparison of the "framing
>   page" and the "top-level browsing context", consider the following
>   scenario: web pages may embed frames with other pages that, in turn,
>   embed frames with other pages as well, and so on.  In theory, this
>   can result in an infinite nesting of framed pages.  For example, web
>   page A may contain web page B in a frame, and web page B may contain
>   web page C in a frame.
>
>   Web page A
>   \<html>
>   ....
>   \<frame src="https://URI_of_web_page_B" />
>   \</html>
>
>   Web page B
>   \<html>
>   ....
>   \<frame src="https://URI_of_web_page_C" />
>   \</html>
>
>   and so forth.
>
>   In this example, for the nested frames with the inner-framed web page
>   C, the most outer web page A would be the "top-level browsing
>   context", and web page B would be the "framing page".

---

https://tools.ietf.org/html/rfc7034#section-4

>   It is important to note that current implementations do not check the
>   origins of the framing resources' entire ancestor tree of frames, and
>   this may expose the resource to attack in multiple-nested scenarios.
>
>   If a resource from origin A embeds untrusted content from origin B,
>   that untrusted content can embed another resource from origin A with
>   an "X-Frame-Options: SAMEORIGIN" policy, and that check would pass
>   when the user agent only verifies the top-level browsing context.
>   Therefore, web developers should be aware that embedding content from
>   other sites can leave their web pages vulnerable to clickjacking even
>   if the X-Frame-Options header is used.

Bug(s):
https://bugzilla.mozilla.org/show_bug.cgi?id=725490

I propose to implement the functionality described.

**Comment by wolfbeast** [comment]
Very straightforward port.
