### ISSUE TITLE
Use the Windows accent color on the title bar and chrome

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/moebius#31]
See MoonchildProductions/Pale-Moon#1222

This needs
- [x] Porting widget code to pick up accent color
- [x] Porting widget code to pick up accent text (based on accent color's luminance)
- [x] Porting widget code for `@media (-moz-windows-accent-color-applies)`
- [x] Porting widget code for `@media (-moz-windows-accent-color-is-dark)`
- [x] Browser theme changes to use the added code
- [x] Change to browser.js/color.jsm to deal with `darkwindowframe`

accent text calculations should use Microsoft's UWP guideline, not WCAG 2.0

**Comment by wolfbeast** [comment]
@Lootyhoof maybe you can lend a hand with the theme changes here? I'm sending you a raw build copy (allowing you to experiment outside of omni.ja)

**Comment by Lootyhoof** [comment]
Hmm..this seems an interesting one. Probably unrelated issue though is that I can't attach DOMi to this - it's complaining about `XML Parsing Error: no root element found Location: chrome://global/content/globalOverlay.xul` (by comparison, Firefox says `Failed to load overlay from chrome://global/content/globalOverlay.xul.` but loads fine)

**Comment by wolfbeast** [comment]
Hmm.. interesting indeed. I'll see if I can figure out what's up with that then.

**Comment by wolfbeast** [comment]
Want me to package it and see if that works any better?

**Comment by Lootyhoof** [comment]
Sure, I'll give that a go.

**Comment by wolfbeast** [comment]
Opened #33 for the `globalOverlay.xul` bug. It's a weird thing to happen since it's apparently called by a debug module... that probably shouldn't even be *in* release builds.

**Comment by Lootyhoof** [comment]
In any case it seems that DOMi now works in the packaged build. Odd..

**Comment by wolfbeast** [comment]
Maybe DOMi itself is trying to load globalOverlay.xul?

**Comment by Lootyhoof** [comment]
Quite possibly. In which case I'm not sure if that's an issue for DOMi or the browser, but either way seems to not be an issue on release builds.

**Comment by wolfbeast** [comment]
OK, preliminary tests are OK for the caption controls, but Australis uses full transparent for inactive tabs and that becomes unreadable. Controls for tabs probably need to be inverted on dark accent colors as well.
![image1](https://user-images.githubusercontent.com/3359132/28462406-6777a806-6e1b-11e7-9f8d-3d58d1aea6a8.png)

**Comment by Lootyhoof** [comment]
Odd...I was sure this was working when I was testing it.

I'll check when I get home and see if maybe there's something I didn't commit properly.

**Comment by wolfbeast** [comment]
Just one remaining issue indicated in #36 -- the "brighttext" property on toolbars doesn't get updated until the window is activated, deactivated or lwtheme changes occur. This prevents window controls from being updated, which is a problem in Australis because of the lack of backgrounds around tab controls.

I've tried a few things to work around this but async internals would cause problems.
I think using a temporary pref set in the widget to be observed by the front-end works, but it needs a bit of a delay to set the brighttext property because otherwise the style isn't computed yet and it won't get picked up or refreshed.
I've set that to 300 ms now which should be short enough to not look wonky, but long enough to have everything refresh properly. I don't like it because it really is very hacky, but it would guarantee that all toolbars will get `brighttext` set on it, so additional toolbars from e.g. extensions could be styled appropriately upon any color change. bonus is that an extension can "poke" the UI to refresh its colors by setting the pref. (`ui.colorChanged`)

The only other way around this is using the `@media(-moz-windows-accent-color-is-dark)` query on the default theme to apply proper toolbar controls (normal or inverted) automatically the moment the accent color changes, instead of relying on `brighttext` for this case. This can probably remain limited to the tab bar, since the bookmarks toolbar and menubar don't really have much to them that require this...

**Comment by wolfbeast** [comment]
Dropped another binary on dropbox, let me know what you think.

**Comment by Lootyhoof** [comment]
LGTM! I'd also suggest porting this to Pale Moon too, since while we don't use transparent tab backgrounds there, we do still have the issue of `brighttext` not being applied at the correct times (e.g. when toolbarbuttons are in `#TabsToolbar` or `#toolbar-menubar`).

**Comment by wolfbeast** [comment]
OK, considering this issue closed then. I'm ported the signal pref across to Pale Moon as well.
