### ISSUE TITLE
macOS: "mach package" complains about missing "basilisk-bin"

### ISSUE THREAD

**Issue by adeshkp** [MoonchildProductions/moebius#315]
Just what it says. `./mach package` expects `basilisk-bin` but this file is not generated by the build command. Doing a simple `ln -s basilisk basilisk-bin` inside build directory shuts it up though. Some changes are needed in the build system to remove this duplicate binary.

https://bugzilla.mozilla.org/show_bug.cgi?id=658850

**Comment by mattatobin** [comment]
That bug is likely irrelevant but deceptively so.

**Comment by mattatobin** [comment]
http://xref.palemoon.org/moebius-trunk/source/application/basilisk/installer/package-manifest.in#128

```
#ifdnef XP_MACOSX
@BINPATH@/@MOZ_APP_NAME@-bin
#endif
```

SHOULD solve it, @adeshkp and let's hope the .app calls the non *-bin version of the binary.. Try it and if successful send a PR

**Comment by adeshkp** [comment]
While the code changes above seem to resolve the issue mentioned, it may not be the right fix as the problem is slightly different. I found that "-bin" file is created, but it is in a different directory.

`$(OBJDIR)/dist/Nightly.app/Contents/MacOS/` contains just `basilisk`
`$(OBJDIR)/dist/Nightly.app/Contents/Resources/` has both `basilisk` and `basilisk-bin`

Not sure how to proceed as I do not have enough knowledge about the build system here. I'm also fairly new to Mac apps, so I might be missing something.

**Comment by wolfbeast** [comment]
Mac should use `@RESPATH@` in the installer manifest. I'm pretty sure that was fixed a long time ago and most paths were converted to ~@RESPATH@` because of this issue (since they are the same on Windows and Linux) so I'm not sure why this would be a problem now and why that states `@BINPATH@`.
