### ISSUE TITLE
Unreachable code after return statement on some JS Modules

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/moebius#322]
Ad https://github.com/MoonchildProductions/Pale-Moon/issues/1244

If you want to solve it:

__Steps to reproduce__
`mach package/installer`:

Ad https://github.com/MoonchildProductions/moebius/commit/fbb1ab598e827598a7619704ff2e40ff63f1b209#diff-dc7d1b10a47be536f4e914faae5170c7R251
`JavaScript warning: resource://gre/modules/NewTabUtils.jsm`
`line 254: unreachable code after return statement`

Ad https://github.com/MoonchildProductions/moebius/commit/a59d09fce4d28d39677de9454da98070fe19f22a#diff-22dbb24a7257410179904e34f5cd62d3R52
`JavaScript warning: resource://app/modules/RecentWindow.jsm`
`line 56: unreachable code after return statement`

Ad https://github.com/MoonchildProductions/moebius/commit/a59d09fce4d28d39677de9454da98070fe19f22a#diff-ce02bb53d129ac1bdec10a9ea87bd7daR842
`JavaScript warning: resource://app/modules/webrtcUI.jsm`
`line 833: unreachable code after return statement`

**Comment by mattatobin** [comment]
These aren't compiler warnings... These are js warnings also the effective evaluation is correct.. They will be solved in time.

**Comment by wolfbeast** [comment]
We are aware of this -- the warnings can be safely ignored.
