### ISSUE TITLE
Privacy issues with Basilisk (and other FF forks)

### ISSUE THREAD

**Issue by anchev** [MoonchildProductions/moebius#326]
Hi,

In the last month I have tested many browsers. Here I think it is worth to mention only Firefox, WaterFox, IceCat, Basilisk. All of them make background connections even with additional tightening of preferences and about:config settings.

I thought I should bring to your attention that Mozilla seems not to respect privacy at all and the attempts to report actual observable privacy issues. I have published the full testing procedure and results in these bug reports (second one being more recent):

https://bugzilla.mozilla.org/show_bug.cgi?id=1424781
https://bugzilla.mozilla.org/show_bug.cgi?id=1432248

Another thing which I found (while testing Basilisk). In about:config I did some brute force cleaning: I zeroed all variables which contained URLs. There were 2-3 for which it wasn't possible, I don't know why. Final result:

+ No background chattering on startup
+ No background chattering on opening preferences
+ Opening https://fsf.org/robots.txt or https://fsf.org communicates only with fsf.org

All this makes me think that such brute force cleanup in about:config may be possible for other Firefox clones. However as I haven't read what each setting does (and there isn't even documentation about everything), this may have some other (probably negative) effects feature-wise. Perhaps you could share if it is at all possible to receive the desired zero-packet background communication. As a whole after all the lengthy tests and the replies of Mozilla: I am questioning the whole Firefox set of forks. If a software is designed in a way which forces the user to sacrifice privacy for security this is clearly a bad design and needs serious reworking (which Mozilla is obviously unwilling to do).

FWIW: Pale Moon doesn't chatter in the background after a little tightening of settings. Unfortunately it doesn't support the latest versions of uMatrix and uBO (or WebExtensions) which I find essential for additional browsing privacy and security.

**Comment by wolfbeast** [comment]
Background connections from the browser are by design (e.g. for update checks).

Please direct dev chatter to the appropriate board on the forum and reserve the issue tracker for actual concrete issues, not perceived issues resulting from the browser's design.

**Comment by anchev** [comment]
This is an actual privacy issue, not an invention.

If a program is designed in a way which forces the user to sacrifice his privacy for externalized services that is surely a design which needs reworking because privacy is a natural expectation in a secure system. Hence the report.

The user is currently unaware that his IP address is sent to Amazon, Akamai and Mozilla automatically with other identifying info and there is no easy way to ensure the privacy level which doesn't include that.

**Comment by wolfbeast** [comment]
This is a general use browser, not a high-sec browser. If you want to use it as a high-sec browser, then you will have to configure it to your needs, it's as simple as that. Sacrificing necessary security updates for privacy reasons has to be an end-user's decision.
