### ISSUE TITLE
Code snapshot of latest release v2018.02.02 ?

### ISSUE THREAD

**Issue by Vangelis66** [MoonchildProductions/moebius#354]
Hello 😃 

At the bottom of the Basilisk download page 
`http://www.basilisk-browser.org/download.shtml` 
there's the following notice/info: 

> **Source code**
> 
> You can find the source code of our releases and tagged commits on [GitHub](https://github.com/MoonchildProductions/moebius/releases). 

_However_, latest release (v2018.02.02) is nowhere to be found, neither inside [Releases](https://github.com/MoonchildProductions/moebius/releases) nor [Tags](https://github.com/MoonchildProductions/moebius/tags). 

I, sadly, am not proficient in the GitHub platform, but am I to assume that the latest release is built from the latest commit (code snapshot) in the "release" branch of this repo, i.e. https://github.com/MoonchildProductions/moebius/commit/6725a8de390bf4228d94309f3f403a6c989e85e0 ?

What I'm really after is the full changelog URI between previous/current release, is then 
https://github.com/MoonchildProductions/moebius/compare/v2018.01.05...6725a8d really it?

Possibly related, and this is just a humble suggestion on my part, but in the case of Firefox Nightly, there exists an `application.ini` file inside the main app dir with related info, e.g. 
```ini
[App]
Vendor=Mozilla
Name=Firefox
RemotingName=firefox
CodeName=Nightly
Version=53.0a1
BuildID=20161117030212
SourceRepository=https://hg.mozilla.org/mozilla-central
SourceStamp=13f49da109ea460665ad27c8497cb1489548450c
ID={ec8030f7-c20a-464f-9b0e-13a3a9e97384}
```
In Basilisk's case, though the same file does exist, the `SourceRepository` & `SourceStamp` entries are missing...
```ini
[App]
Vendor=Moonchild Productions
Name=Basilisk
RemotingName=basilisk
Version=55.0.2018.01.05
BuildID=20180105004734
ID={ec8030f7-c20a-464f-9b0e-13a3a9e97384}
```
Additionally, in Nightly, `about:buildconfig` provides immediate info on the code snapshot it originated from: 
```
about:buildconfig

Source

Built from https://hg.mozilla.org/mozilla-central/rev/13f49da109ea460665ad27c8497cb1489548450c
``` 
while, again, `about:buildconfig` in Basilisk provides no clue about the source... 😞 

So, in fact, what I'm kindly requesting is you implement a way (not necessarily the Mozilla one) by which any given downloaded basilisk binary could easily reveal the source code it's built from... 

Many thanks for your on-going coding efforts!

**Comment by wolfbeast** [comment]
Or, instead of asking for elaborate code changes, just a reminder that the release wasn't tagged or the tag wasn't pushed. This has been done now.

**Comment by mattatobin** [comment]
For the record, this has been looked into a couple of times over the years. As implimented right now it is a bit annoying as it only kinda works with the git and only if the mozillabuild package is aware of it.

I do know how to manually retreve the info without git and have done so with both python and php.

Still, to make this universally work would require some thinking and we do have bigger fish to fry.
