### ISSUE TITLE
TabMixPlus extension does not display multiline tabs area

### ISSUE THREAD

**Issue by kkm000** [MoonchildProductions/moebius#355]
Basilisk 2018.02.02 (64-bit), TMP 0.5.04.

When I enable multiline tab option, tabs do form multiple lines, but only one line is shown. Pointing mouse to the tab row and scrolling with the mouse scrolls tab rows on the bar, but only one row is displayed at a time. The same extension works in FF 52.6.0 (32-bit) ESR. I have not tested FF 64 bit -- is there any difference in how XUL is handled in different build bitness?

I am a software engineer, but know not much about XUL. I know there are some magic `chrome://` URIs I can use to open XUL in the window and examine it with the debugger, but I did not know how to find the URL. If I do, I might be able to poke around to provide more info. 

In any case, if you need any additional info, please let me know! Just in case, I exported TMP preferences from working FF installation, and imported the file into Basilisk; that did not help. I am attaching the file to the ticket.

[TMPpref.txt](https://github.com/MoonchildProductions/moebius/files/1693994/TMPpref.txt)

**Comment by mattatobin** [comment]
Please contact the extension developer.
