### ISSUE TITLE
WebExtensions - SwitchyOmega resets to System Proxy on startup

### ISSUE THREAD

**Issue by Baddest-Juju** [MoonchildProductions/moebius#356]
When the browser starts up, you can visibly see SwitchyOmega being switched from the profile you had selected last time over to System Proxy. This occurs even if you set this in SwitchyOmega's settings:

![image](https://user-images.githubusercontent.com/33403660/36085552-1201335c-0f8c-11e8-864f-223246c40ad9.png)

This behavior does not occur on Firefox Quantum.

This is probably indicative of a larger bug outside of just using SwitchyOmega so I figured this would be worth posting.

**Comment by wolfbeast** [comment]
Or it's just indicative of SwitchOmega (which I've never heard of before now, and have no clue what it does) not catering to Basilisk properly. Keep in mind that if there's an issue with extensions to a browser not working properly, it is normally the extension dev's task to fix it.

For us to look at this on the browser side, it needs to become clear first that there is indeed a browser bug involved. A lot more information is needed for that, that usually only the extension dev can provide.

**Comment by Baddest-Juju** [comment]
Why does Basilisk need to be catered to? If it's behaving correctly on Firefox Quantum but not on Basilisk, is that not indicative of a bug?

It's just a bit frustrating because there doesn't seem to be any reliable way for me to set up a proxy with authentication under Basilisk at the moment, other than using something like privoxy to proxy the proxy.

**Comment by wolfbeast** [comment]
Extensions extend a browser, not the other way around. Firefox Quantum is not Basilisk. they are essentially different. If you call that difference a "bug" then you don't seem to understand what forks are.

**Comment by Baddest-Juju** [comment]
¯\_(ツ)_/¯

**Comment by Sa-Ja-Di** [comment]
@Baddest-Juju Basilisk has an experimental Webextensions support. AS it is a fork, it means there is no constant exchange of code elements from latest Firefox engine versions possible.

People want Webextensions to work better? People can either gather info's how to do that or ask others for helping the Pale Moon project.
