### ISSUE TITLE
Extension: Stylish/Stylus

### ISSUE THREAD

**Issue by nufrankz** [MoonchildProductions/moebius#357]
Being installed both of them, website [userstyles.org](https://userstyles.org) can't detect them installed.

[Stylus](https://addons.mozilla.org/en-US/firefox/addon/styl-us/)
[Stylish](https://addons.mozilla.org/es/firefox/addon/stylish/)

Basilisk 2018.02.14 (32-bit)

Thanks!

**Comment by wolfbeast** [comment]
Interaction between extension (not our code) and website (not our code) -> not our bug.

**Comment by CitoplasmaX** [comment]
I believe that an extension installed and not detected is your bug. Maybe it is need a firefox test with the extension to probe that it is not an extension bug.

**Comment by wolfbeast** [comment]
@CitoplasmaX then please provide information about the actual bug in the browser. Detection based on assumptions of e.g. browser name, UA, or names of functions inside the browser is not a browser bug.

**Comment by CitoplasmaX** [comment]
Many firefox extensions works by default in basilisk, then if the extension is compatible with the same firefox version in with basilisk is based on, then this => "browser name, UA, or names of functions inside the browser" should not have to see **at now**. In the future, if you change this, you should provide a list of compatible extensions or it will be also your problem.

**Comment by wolfbeast** [comment]
It is not our responsibility to make extensions compatible with us. Since you've resorted to stating generics, I'm assuming there is no actual bug here.
