### ISSUE TITLE
Modern versions of extenstion "Decentraleyes" and "Privacy Settings" not supported on Basilisk

### ISSUE THREAD

**Issue by gothicale** [MoonchildProductions/moebius#358]
This is my first post here, but Basilisk only seems to support, at latest, Decentraleyes 1.3.0. It also doesn't support Privacy Settings at all. Please fix these important privacy extensions.

**Comment by mattatobin** [comment]
It is not the job of the application to be compatible with extensions.. It is the job of extensions to be compatible with the application.

Please contact the developer of the extension.

**Comment by Sa-Ja-Di** [comment]
@gothicale 

Webextensions? Keep in mind that Basilisk only has experimental support for them. As that is a fork with a different goal, staying up to date with all the new  webextension API is not the main goal here.

You want more webextension compatibility? Find someone who ports them to UXP or find out how to do it on your own :)
