### ISSUE TITLE
Bug: Bookmarking all tabs crashes Basilisk 2018.03.21 (64-bit)

### ISSUE THREAD

**Issue by TerraformerX** [MoonchildProductions/moebius#361]
First of all, Basilisk almost immediately became my favorite browser, and I definitely prefer Moonchild browsers over all others.

But every time I right-click on a tab and select "Bookmark All Tabs", Basilisk crashes. Usually it crashes immediately after successfully bookmarking all the tabs in the folder I specified, but this time, it seems it didn't crash until I opened the folder from my bookmarks toolbar to confirm they were there.

I have a small script in my .bashrc file, so that whenever I open a terminal, it displays the date. I prefer to file my bookmarks in folders named by the date. So when I want to bookmark all tabs, I right-click on a tab, select "Bookmark All Tabs", then I open a terminal, double-click the date, copy it, then Alt+Tab back to the bookmark dialog box, select all text in the folder text box, paste the date from the clipboard, select the folder I want in the directory tree, and then click "Add Bookmarks".

My version of Basilisk is: 2018.03.21 (64-bit)
My distribution of Linux: Linux Mint 18.3 Sylvia MATE
uname -a: Linux computername 4.13.0-36-generic #40~16.04.1-Ubuntu SMP Fri Feb 16 23:25:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

I am currently on the basilisk-release update channel.

Edit: Even though Basilisk crashes after clicking "Add Bookmarks", I've never seen it fail to successfully add the bookmarks in the folder directory I specified.

**Comment by trav90** [comment]
Can you start Basilisk from the terminal and post any messages you get when it crashes?

**Comment by TerraformerX** [comment]
Ok, I disabled all the add-ons, and then restarted Basilisk. I started it from the command line again, and once again right-clicked a tab, and bookmarked all tabs, but it still crashed with no add-ons.

```
user@computer:~$ /home/user/Downloads/basilisk/basilisk

(basilisk:3776): GLib-GObject-WARNING **: /build/glib2.0-prJhLS/glib2.0-2.48.2/./gobject/gsignal.c:3486: signal name 'selection_changed' is invalid for instance '0x7f0514c70ce0' of type 'MaiAtkType3'

(basilisk:3776): GLib-GObject-WARNING **: /build/glib2.0-prJhLS/glib2.0-2.48.2/./gobject/gsignal.c:3486: signal name 'selection_changed' is invalid for instance '0x7f0514c70ce0' of type 'MaiAtkType3'

(basilisk:3776): GLib-GObject-WARNING **: /build/glib2.0-prJhLS/glib2.0-2.48.2/./gobject/gsignal.c:3486: signal name 'selection_changed' is invalid for instance '0x7f0514c70ce0' of type 'MaiAtkType3'

(basilisk:3776): GLib-GObject-WARNING **: /build/glib2.0-prJhLS/glib2.0-2.48.2/./gobject/gsignal.c:3486: signal name 'selection_changed' is invalid for instance '0x7f0515737d80' of type 'MaiAtkType3'

(basilisk:3776): GLib-GObject-WARNING **: /build/glib2.0-prJhLS/glib2.0-2.48.2/./gobject/gsignal.c:3486: signal name 'selection_changed' is invalid for instance '0x7f0515737d80' of type 'MaiAtkType3'

(basilisk:3776): GLib-GObject-WARNING **: /build/glib2.0-prJhLS/glib2.0-2.48.2/./gobject/gsignal.c:3486: signal name 'selection_changed' is invalid for instance '0x7f051299ec90' of type 'MaiAtkType3'

(basilisk:3776): GLib-GObject-WARNING **: /build/glib2.0-prJhLS/glib2.0-2.48.2/./gobject/gsignal.c:3486: signal name 'selection_changed' is invalid for instance '0x7f051299ec90' of type 'MaiAtkType3'

(basilisk:3776): GLib-GObject-WARNING **: /build/glib2.0-prJhLS/glib2.0-2.48.2/./gobject/gsignal.c:3486: signal name 'selection_changed' is invalid for instance '0x7f051299ec90' of type 'MaiAtkType3'

(basilisk:3776): GLib-GObject-WARNING **: /build/glib2.0-prJhLS/glib2.0-2.48.2/./gobject/gsignal.c:3486: signal name 'selection_changed' is invalid for instance '0x7f05260c4b50' of type 'MaiAtkType3'

(basilisk:3776): GLib-GObject-WARNING **: /build/glib2.0-prJhLS/glib2.0-2.48.2/./gobject/gsignal.c:3486: signal name 'selection_changed' is invalid for instance '0x7f05260c4b50' of type 'MaiAtkType3'
Segmentation fault (core dumped)
user@computer:~$ ```

**Comment by trav90** [comment]
I followed the steps you listed above this morning in a fresh profile and did not experience any crash. Perhaps see if the issue persists in a new profile?

**Comment by TerraformerX** [comment]
Alright, I made a new profile, and logged into it. I opened Basilisk on the command line, and proceeded to open some tabs to random websites so that I would have some tabs to bookmark. However, opening new tabs seems to crash Baslisk also. Here was the std output on the terminal:
```
newuser@computer ~ $ Downloads/basilisk/basilisk
[Parent 8304] WARNING: pipe error (65): Connection reset by peer: file /home/trava90/UXP/moebius-2018.03.21/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 346
[Parent 8304] WARNING: pipe error (63): Connection reset by peer: file /home/trava90/UXP/moebius-2018.03.21/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 346

###!!! [Parent][MessageChannel] Error: (msgtype=0x2C0085,name=PBrowser::Msg_Destroy) Channel error: cannot send/recv

[Parent 8304] WARNING: pipe error (56): Connection reset by peer: file /home/trava90/UXP/moebius-2018.03.21/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 346
[Parent 8304] WARNING: pipe error (62): Connection reset by peer: file /home/trava90/UXP/moebius-2018.03.21/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 346

###!!! [Parent][MessageChannel] Error: (msgtype=0x2C0085,name=PBrowser::Msg_Destroy) Channel error: cannot send/recv

[Parent 8304] WARNING: pipe error (109): Connection reset by peer: file /home/trava90/UXP/moebius-2018.03.21/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 346
[Parent 8304] WARNING: pipe error (57): Connection reset by peer: file /home/trava90/UXP/moebius-2018.03.21/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 346

###!!! [Parent][MessageChannel] Error: (msgtype=0x2C0085,name=PBrowser::Msg_Destroy) Channel error: cannot send/recv

Segmentation fault (core dumped)
newuser@computer ~ $ Downloads/basilisk/basilisk
[Parent 8561] WARNING: pipe error (69): Connection reset by peer: file /home/trava90/UXP/moebius-2018.03.21/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 346
[Parent 8561] WARNING: pipe error (61): Connection reset by peer: file /home/trava90/UXP/moebius-2018.03.21/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 346

###!!! [Parent][MessageChannel] Error: (msgtype=0x2C0085,name=PBrowser::Msg_Destroy) Channel error: cannot send/recv

Segmentation fault (core dumped)
newuser@computer ~ $ 
```

**Comment by wolfbeast** [comment]
Are you perhaps having very tight restrictions on loopback networking?

**Comment by TerraformerX** [comment]
My /etc/network/interfaces file is the default. I do have iptables running, but I'm not savvy with it. How should I check what you're asking?

**Comment by wolfbeast** [comment]
Closing this to archive Möbius. If this is still an issue in the current UXP Basilisk, please open a new issue on the UXP repo.
