### ISSUE TITLE
Curious about mimeTypes.rdf

### ISSUE THREAD

**Issue by Lorienna** [MoonchildProductions/moebius#39]
_mimeTypes.rdf_ will be replaced by _handlers.json_ from FF 55 on ([`bug 1287658`](https://bugzilla.mozilla.org/show_bug.cgi?id=1287658), [`changeset 356703`](https://hg.mozilla.org/mozilla-central/rev/97a69c3ff07c)), so I'm wondering whether it will stay on UXP?

**Comment by wolfbeast** [comment]
I see no reason to put in the extra work to "jsonificate" the MIME type storage. For example, to do this, we'd also have to write a new implementation of nsIHandlerService for the JSON storage format...
There's nothing wrong with RDF. We know the format, we use RDF parsing in plenty of other places, and there's no reason I can see that makes JSON a better storage format for this.

**Comment by Lorienna** [comment]
I see, thanks. Two more questions, if you don't mind.

## 1)

> we'd also have to write a new implementation of nsIHandlerService for the JSON storage format

They've made some changes to `nsIHandlerService` on 52.0a1 (2016-11-11) nightly:

[Bug 1287664](https://bugzilla.mozilla.org/show_bug.cgi?id=1287664) - Revise _helperApp.js_ and(/or) enhance `nsIHandlerService` API based on the result of __bug 1287661__.
[Changeset 321882](https://hg.mozilla.org/mozilla-central/rev/bb7b525fe7e7) - Replacing useless module _HelperApps.js_ by using `nsIHandlerService`. r=Paolo.

This also led to some differences between entries on PM 27.4 and FF 52-54 (missing lines on FF being marked red):

```diff
  <RDF:Description RDF:about="urn:mimetype:application/zip"
                   NC:value="application/zip"
-                  NC:editable="true"
                   NC:fileExtensions="zip"
-                  NC:description="WinRAR ZIP archive">
    <NC:handlerProp RDF:resource="urn:mimetype:handler:application/zip"/>
  </RDF:Description>
```
```diff
  <RDF:Description RDF:about="urn:mimetype:handler:application/zip"
                   NC:alwaysAsk="true"
                   NC:saveToDisk="true">
-   <NC:externalApplication RDF:resource="urn:mimetype:externalApplication:application/zip"/>
  </RDF:Description>
```

---

__Question:__ could this changeset be related to that quote above, and if so, are you going to keep it on UXP or revert it to an earlier state?

## 2)

The 30boxes.com link was changed from `http://` to `https://` on 25.0a1 (2013-07-24) nightly ([bug 840699](https://bugzilla.mozilla.org/show_bug.cgi?id=840699), [changeset 139834](https://hg.mozilla.org/mozilla-central/rev/74633f25ca05)).

The differences are as follows, with the red lines belonging to PM here, green - to FF:

```diff
  <RDF:Description RDF:about="urn:root"
-                  NC:en-US_defaultHandlersVersion="3" />
+                  NC:en-US_defaultHandlersVersion="4" />
```
```diff
- <RDF:Description RDF:about="urn:handler:web:http://30boxes.com/external/widget?refer=ff&amp;url=%s"
+ <RDF:Description RDF:about="urn:handler:web:https://30boxes.com/external/widget?refer=ff&amp;url=%s"
                   NC:prettyName="30 Boxes"
-                  NC:uriTemplate="http://30boxes.com/external/widget?refer=ff&amp;url=%s" />
+                  NC:uriTemplate="https://30boxes.com/external/widget?refer=ff&amp;url=%s" />
```
```diff
  <RDF:Description RDF:about="urn:scheme:handler:webcal"
                   NC:alwaysAsk="true">
-   <NC:possibleApplication RDF:resource="urn:handler:web:http://30boxes.com/external/widget?refer=ff&amp;url=%s"/>
+   <NC:possibleApplication RDF:resource="urn:handler:web:https://30boxes.com/external/widget?refer=ff&amp;url=%s"/>
  </RDF:Description>
```

---

__Question:__ will `https://` be kept for 30boxes.com, given that the site's security certificate expired in 2014?

**Comment by Lorienna** [comment]
I've updated the questions to be (hopefully) a bit more clear, and if everything in _mimeTypes.rdf_ is going to be left exactly as it is now then probably the issue can be closed...

**Comment by wolfbeast** [comment]
https://github.com/MoonchildProductions/moebius/issues/39#issuecomment-318062447
