### ISSUE TITLE
URL API: add toJSON support

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/moebius#48]
https://url.spec.whatwg.org/#dom-url-tojson

> The href attribute’s getter and the toJSON() method, when invoked, must return the serialization of context object’s url. 

---

You add the label `Standards Compliance`, please.

**Comment by wolfbeast** [comment]
Can this be closed?

**Comment by janekptacijarabaci** [comment]
IMHO: yes

**Comment by janekptacijarabaci** [comment]
IMHO: yes
