### ISSUE TITLE
DevTools - Scratchpad/Style editor - Main/Context menu: Edit - "Find", "Find Again", "Jump    to line" - does not work

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/moebius#51]
Keyboard shortcuts works (only).

See also:
https://github.com/MoonchildProductions/Pale-Moon/pull/1274

---

You add the label `Devtools`, please.

**Comment by janekptacijarabaci** [comment]
See also https://bugzilla.mozilla.org/show_bug.cgi?id=1397366

Pushlog:
https://hg.mozilla.org/integration/autoland/pushloghtml?fromchange=88a8ec4889026852ce8a9c59534d67a767e5bc95&tochange=3470e326025c62381dc5f7c06629dbe5dbd7f242

[Bug 1292592](https://bugzilla.mozilla.org/show_bug.cgi?id=1292592) is the suspect.

**Comment by mattatobin** [comment]
So is there any movement on this?
