### ISSUE TITLE
JS - DOM - implement document.onvisibilitychange

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/moebius#75]
https://w3c.github.io/page-visibility/#extensions-to-the-document-interface

> The Page Visibility API defines a means to programmatically determine the visibility state 
of a top level browsing context, and to be notified if the visibility state changes. Without 
knowing the visibility state of a page, web developers have been designing web pages as if 
they are always visible. This not only results in higher machine resource utilization, but it 
prevents web developers from making runtime decisions based on whether the web page is visible 
to the user. Designing web pages with knowledge of the page's visibility state can result in 
improved user experiences and power efficient sites. 

> With this API, web applications can choose to alter their behavior based on whether they are 
visible to the user or not. For example, this API can be used to scale back work when the page 
is no longer visible. 

See also:
https://github.com/MoonchildProductions/Pale-Moon/issues/1276

**Comment by wolfbeast** [comment]
Verified with http://w3c-test.org/page-visibility/idlharness.html
