### ISSUE TITLE
Remove b2g

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/moebius#8]
`/b2g` (Firefox OS) is completely dead code for us. We shouldn't have it in our tree or weaved into our build system.

This needs to go.

---
- [x] Remove B2G Application Tree
- [x] Remove MOZ_B2G code
- [x] Remove MOZ_MULET garbage

**Comment by mattatobin** [comment]
I am gonna take this..

- [ ] Remove B2G Application Tree
- [ ] Remove ifdef'd code
- [ ] Remove configure code (Not going to do this until I figure out what I am gonna do about configure)
