### ISSUE TITLE
[draft] JS - DOM - implement animationcancel event

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/moebius#85]
https://drafts.csswg.org/css-animations/#eventdef-animationevent-animationcancel

> animationcancel

> The animationcancel event occurs when the animation stops running in a way that does not
fire an animationend event, such as a change in the animation-name that removes the animation, or the animating element or one of its ancestors becoming display:none.

> The elapsedTime member for this event indicates the number of seconds that had elapsed since the beginning of the animation at the moment when the animation was canceled. This excludes any time where the animation was paused. If the animation had a negative animation-delay, the beginning of the animation is the moment equal to the absolute value of animation-delay seconds prior to when the animation was actually triggered. Alternatively, if the animation had a positive animation-delay and the event is fired before the animation’s delay has expired, the elapsedTime will be zero.

> Bubbles: Yes
> Cancelable: No
> Context Info: animationName, elapsedTime, pseudoElement

**Comment by wolfbeast** [comment]
Note: At this time, no major browser supports animationcancel. This will likely go completely unused.

**Comment by wolfbeast** [comment]
Verified with the MDN page that has a live demo.
