### ISSUE TITLE
HTML - implement the labels attribute

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/moebius#86]
https://www.w3.org/TR/html5/forms.html#dom-lfe-labels

> Labelable elements have a NodeList object associated with them that represents the list of label elements, in tree order, whose labeled control is the element in question. The labels IDL attribute of labelable elements, on getting, must return that NodeList object.

**Comment by wolfbeast** [comment]
Verified with https://jsfiddle.net/api/mdn/
