### ISSUE TITLE
Build fails at Rust target

### ISSUE THREAD

**Issue by Happy-Ferret** [MoonchildProductions/moebius#94]
OS:  **Windows 8 Pro/64bit** (the same can also be reproduced on my Windows 10 Professional/64 Bit machine at home though).

Rustc: 1.19.0-nightly

Compiler Suite: **Visual Studio 2015 Update 3**

Mozilla-Build: **2.2.0**

Command run: ```mach build```

Summary:

Dying to know what WebP support in Moebius/UXP looks like, I cloned the repository and attempted to
build the project running ```mach build```.

Unfortunately, after roughly 50 minutes that build was aborted, yielding the following error message.

Traceback: 

```50:13.76 error: the lock file needs to be updated but --locked was passed to prevent this
50:13.80 c:/Users/User/Desktop/Gitlab/forks/moebius/config/rules.mk:966: recipe for target 'force-cargo-library-build' failed
50:13.83 mozmake.EXE[5]: *** [force-cargo-library-build] Error 101
50:13.84 c:/Users/User/Desktop/Gitlab/forks/moebius/config/recurse.mk:71: recipe for target 'toolkit/library/gtest/rust/target' failed```

**Comment by trav90** [comment]
You need to use the --disable-rust mozconifg option.

**Comment by Happy-Ferret** [comment]
Thank you.

Adding ```ac_add_options --disable-rust``` to ```.mozconfig``` did indeed do the deed.

Just wondering. What are the plans (if there are any) for Rust support in the core?
Will Goanna include Rust components found in Servo or retain its own rendering code instead?

**Comment by wolfbeast** [comment]
We'll be removing rust components -- there are no plans for using Servo components.

**Comment by wolfbeast** [comment]
Depends on #96
